/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ServiceM8Error } from "./servicem8error.js";

export type RateLimitErrorData = {
  errorCode?: number | undefined;
  message?: string | undefined;
};

export class RateLimitError extends ServiceM8Error {
  errorCode?: number | undefined;

  /** The original data that was passed to this error instance. */
  data$: RateLimitErrorData;

  constructor(
    err: RateLimitErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.errorCode != null) this.errorCode = err.errorCode;

    this.name = "RateLimitError";
  }
}

/** @internal */
export const RateLimitError$inboundSchema: z.ZodType<
  RateLimitError,
  z.ZodTypeDef,
  unknown
> = z.object({
  errorCode: z.number().optional(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RateLimitError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type RateLimitError$Outbound = {
  errorCode?: number | undefined;
  message?: string | undefined;
};

/** @internal */
export const RateLimitError$outboundSchema: z.ZodType<
  RateLimitError$Outbound,
  z.ZodTypeDef,
  RateLimitError
> = z.instanceof(RateLimitError)
  .transform(v => v.data$)
  .pipe(z.object({
    errorCode: z.number().optional(),
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RateLimitError$ {
  /** @deprecated use `RateLimitError$inboundSchema` instead. */
  export const inboundSchema = RateLimitError$inboundSchema;
  /** @deprecated use `RateLimitError$outboundSchema` instead. */
  export const outboundSchema = RateLimitError$outboundSchema;
  /** @deprecated use `RateLimitError$Outbound` instead. */
  export type Outbound = RateLimitError$Outbound;
}
