/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { allocationWindowsGetAllocationWindows } from "../../funcs/allocationWindowsGetAllocationWindows.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllocationWindowsRequest$inboundSchema,
};

export const tool$allocationWindowsGetAllocationWindows: ToolDefinition<
  typeof args
> = {
  name: "allocation-windows-get-allocation-windows",
  description: `Retrieve an Allocation Window


			
#### OAuth Scope
This endpoint requires the following OAuth scope **read_schedule**.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await allocationWindowsGetAllocationWindows(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
