/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetTypesCreateAssetTypes } from "../../funcs/assetTypesCreateAssetTypes.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.AssetTypeCreate$inboundSchema,
};

export const tool$assetTypesCreateAssetTypes: ToolDefinition<typeof args> = {
  name: "asset-types-create-asset-types",
  description: `Create a new Asset Type


			
#### OAuth Scope
This endpoint requires the following OAuth scope **manage_assets**.

			
			
#### Record UUID
UUID is optional for record creation. If no UUID is supplied, a UUID will be automatically generated for the new record and returned in the \`x-record-uuid\` response header.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assetTypesCreateAssetTypes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
