/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { clientsCreateClients } from "../../funcs/clientsCreateClients.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CompanyInput$inboundSchema,
};

export const tool$clientsCreateClients: ToolDefinition<typeof args> = {
  name: "clients-create-clients",
  description: `Create a new Client


			
#### OAuth Scope
This endpoint requires the following OAuth scope **manage_customers**.

			
			
#### Record UUID
UUID is optional for record creation. If no UUID is supplied, a UUID will be automatically generated for the new record and returned in the response header as x-record-uuid.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await clientsCreateClients(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
