/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { clientsGetClients } from "../../funcs/clientsGetClients.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetClientsRequest$inboundSchema,
};

export const tool$clientsGetClients: ToolDefinition<typeof args> = {
  name: "clients-get-clients",
  description: `Retrieve a Client


			
#### OAuth Scope
This endpoint requires the following OAuth scope **read_customers**.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await clientsGetClients(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
