/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { emailTemplatesCreateEmailTemplates } from "../../funcs/emailTemplatesCreateEmailTemplates.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.EmailTemplateInput$inboundSchema,
};

export const tool$emailTemplatesCreateEmailTemplates: ToolDefinition<
  typeof args
> = {
  name: "email-templates-create-email-templates",
  description: `Create a new Email Template


			
#### Record UUID
UUID is optional for record creation. If no UUID is supplied, a UUID will be automatically generated for the new record and returned in the response header as x-record-uuid.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await emailTemplatesCreateEmailTemplates(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
