/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { formFieldsGetFormFields } from "../../funcs/formFieldsGetFormFields.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetFormFieldsRequest$inboundSchema,
};

export const tool$formFieldsGetFormFields: ToolDefinition<typeof args> = {
  name: "form-fields-get-form-fields",
  description: `Retrieve a Form Field`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await formFieldsGetFormFields(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
