/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { formsDeleteForms } from "../../funcs/formsDeleteForms.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteFormsRequest$inboundSchema,
};

export const tool$formsDeleteForms: ToolDefinition<typeof args> = {
  name: "forms-delete-forms",
  description: `Delete a Form


			
In ServiceM8, records are never deleted, but are archived. Archived records will remain accessible via the API as (active = 0), however will no longer be visible in UI. Archived records can be restored to active by setting the record active field to 1.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await formsDeleteForms(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
