/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { inboxGetInboxMessage } from "../../funcs/inboxGetInboxMessage.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetInboxMessageRequest$inboundSchema,
};

export const tool$inboxGetInboxMessage: ToolDefinition<typeof args> = {
  name: "inbox-get-inbox-message",
  description: `Get inbox message details

Retrieves detailed information about a specific inbox message including attachments and conversation history`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await inboxGetInboxMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
