/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobPaymentsGetJobPayments } from "../../funcs/jobPaymentsGetJobPayments.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetJobPaymentsRequest$inboundSchema,
};

export const tool$jobPaymentsGetJobPayments: ToolDefinition<typeof args> = {
  name: "job-payments-get-job-payments",
  description: `Retrieve a Job Payment


			
#### OAuth Scope
This endpoint requires the following OAuth scope **read_job_payments**.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await jobPaymentsGetJobPayments(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
