/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobPaymentsUpdateJobPayments } from "../../funcs/jobPaymentsUpdateJobPayments.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateJobPaymentsRequest$inboundSchema,
};

export const tool$jobPaymentsUpdateJobPayments: ToolDefinition<typeof args> = {
  name: "job-payments-update-job-payments",
  description: `Update a Job Payment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await jobPaymentsUpdateJobPayments(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
