/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobQueuesDeleteJobQueues } from "../../funcs/jobQueuesDeleteJobQueues.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteJobQueuesRequest$inboundSchema,
};

export const tool$jobQueuesDeleteJobQueues: ToolDefinition<typeof args> = {
  name: "job-queues-delete-job-queues",
  description: `Delete a Job Queue


			
In ServiceM8, deleting a record sets its \`active\` field to \`0\`. Inactive records are still accessible on the API, but are hidden in the UI. Inactive records can be restored by setting their \`active\` field to \`1\`.

			
			
#### OAuth Scope
This endpoint requires the following OAuth scope **manage_job_queues**.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await jobQueuesDeleteJobQueues(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
