/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobTemplatesListJobTemplates } from "../../funcs/jobTemplatesListJobTemplates.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$jobTemplatesListJobTemplates: ToolDefinition = {
  name: "job-templates-list-job-templates",
  description: `List all Job Templates


			
#### Filtering
This endpoint supports result filtering. For more information on how to filter this request, [go here](/docs/filtering).
			
			
#### OAuth Scope
This endpoint requires the following OAuth scope **read_jobs**.

			`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await jobTemplatesListJobTemplates(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
