/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeArticlesListKnowledgeArticles } from "../../funcs/knowledgeArticlesListKnowledgeArticles.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$knowledgeArticlesListKnowledgeArticles: ToolDefinition = {
  name: "knowledge-articles-list-knowledge-articles",
  description: `List all Knowledge Articles


			
#### Filtering
This endpoint supports result filtering. For more information on how to filter this request, [go here](/docs/filtering).
			
			
#### OAuth Scope
This endpoint requires the following OAuth scope **read_knowledge**.

			`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await knowledgeArticlesListKnowledgeArticles(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
