/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notesUpdateNotes } from "../../funcs/notesUpdateNotes.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateNotesRequest$inboundSchema,
};

export const tool$notesUpdateNotes: ToolDefinition<typeof args> = {
  name: "notes-update-notes",
  description: `Update a Note


			
#### OAuth Scope
This endpoint requires the following OAuth scope **publish_job_notes**.

			`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notesUpdateNotes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
