/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsDeleteAssets } from "../funcs/assetsDeleteAssets.js";
import { assetsGetAssets } from "../funcs/assetsGetAssets.js";
import { assetsListAssets } from "../funcs/assetsListAssets.js";
import { assetsUpdateAssets } from "../funcs/assetsUpdateAssets.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Assets extends ClientSDK {
  /**
   * List all Assets
   *
   * @remarks
   *
   * #### Filtering
   * This endpoint supports result filtering. For more information on how to filter this request, [go here](/docs/filtering).
   *
   * #### OAuth Scope
   * This endpoint requires the following OAuth scope **read_assets**.
   */
  async listAssets(
    security: operations.ListAssetsSecurity,
    options?: RequestOptions,
  ): Promise<operations.ListAssetsResponse> {
    return unwrapAsync(assetsListAssets(
      this,
      security,
      options,
    ));
  }

  /**
   * Retrieve an Asset
   *
   * @remarks
   *
   * #### OAuth Scope
   * This endpoint requires the following OAuth scope **read_assets**.
   */
  async getAssets(
    security: operations.GetAssetsSecurity,
    request: operations.GetAssetsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAssetsResponse> {
    return unwrapAsync(assetsGetAssets(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update an Asset
   */
  async updateAssets(
    security: operations.UpdateAssetsSecurity,
    request: operations.UpdateAssetsRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateAssetsResponse> {
    return unwrapAsync(assetsUpdateAssets(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete an Asset
   *
   * @remarks
   *
   * In ServiceM8, deleting a record sets its `active` field to `0`. Inactive records are still accessible on the API, but are hidden in the UI. Inactive records can be restored by setting their `active` field to `1`.
   */
  async deleteAssets(
    security: operations.DeleteAssetsSecurity,
    request: operations.DeleteAssetsRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteAssetsResponse> {
    return unwrapAsync(assetsDeleteAssets(
      this,
      security,
      request,
      options,
    ));
  }
}
