/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobMaterialBundlesCreateJobMaterialBundles } from "../funcs/jobMaterialBundlesCreateJobMaterialBundles.js";
import { jobMaterialBundlesDeleteJobMaterialBundles } from "../funcs/jobMaterialBundlesDeleteJobMaterialBundles.js";
import { jobMaterialBundlesGetJobMaterialBundles } from "../funcs/jobMaterialBundlesGetJobMaterialBundles.js";
import { jobMaterialBundlesListJobMaterialBundles } from "../funcs/jobMaterialBundlesListJobMaterialBundles.js";
import { jobMaterialBundlesUpdateJobMaterialBundles } from "../funcs/jobMaterialBundlesUpdateJobMaterialBundles.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class JobMaterialBundles extends ClientSDK {
  /**
   * List all Job Material Bundles
   *
   * @remarks
   *
   * #### Filtering
   * This endpoint supports result filtering. For more information on how to filter this request, [go here](/docs/filtering).
   *
   * #### OAuth Scope
   * This endpoint requires the following OAuth scope **read_job_materials**.
   */
  async listJobMaterialBundles(
    options?: RequestOptions,
  ): Promise<Array<components.JobMaterialBundle>> {
    return unwrapAsync(jobMaterialBundlesListJobMaterialBundles(
      this,
      options,
    ));
  }

  /**
   * Create a new Job Material Bundle
   *
   * @remarks
   *
   * #### OAuth Scope
   * This endpoint requires the following OAuth scope **manage_job_materials**.
   *
   * #### Record UUID
   * UUID is optional for record creation. If no UUID is supplied, a UUID will be automatically generated for the new record and returned in the `x-record-uuid` response header.
   */
  async createJobMaterialBundles(
    request: components.JobMaterialBundleCreate,
    options?: RequestOptions,
  ): Promise<operations.CreateJobMaterialBundlesResponse> {
    return unwrapAsync(jobMaterialBundlesCreateJobMaterialBundles(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a Job Material Bundle
   *
   * @remarks
   *
   * #### OAuth Scope
   * This endpoint requires the following OAuth scope **read_job_materials**.
   */
  async getJobMaterialBundles(
    request: operations.GetJobMaterialBundlesRequest,
    options?: RequestOptions,
  ): Promise<components.JobMaterialBundle> {
    return unwrapAsync(jobMaterialBundlesGetJobMaterialBundles(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a Job Material Bundle
   *
   * @remarks
   *
   * #### OAuth Scope
   * This endpoint requires the following OAuth scope **manage_job_materials**.
   */
  async updateJobMaterialBundles(
    request: operations.UpdateJobMaterialBundlesRequest,
    options?: RequestOptions,
  ): Promise<components.Result> {
    return unwrapAsync(jobMaterialBundlesUpdateJobMaterialBundles(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a Job Material Bundle
   *
   * @remarks
   *
   * In ServiceM8, deleting a record sets its `active` field to `0`. Inactive records are still accessible on the API, but are hidden in the UI. Inactive records can be restored by setting their `active` field to `1`.
   *
   * #### OAuth Scope
   * This endpoint requires the following OAuth scope **manage_job_materials**.
   */
  async deleteJobMaterialBundles(
    request: operations.DeleteJobMaterialBundlesRequest,
    options?: RequestOptions,
  ): Promise<components.Result> {
    return unwrapAsync(jobMaterialBundlesDeleteJobMaterialBundles(
      this,
      request,
      options,
    ));
  }
}
