/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ArchiveInboxMessageRequest = {
  /**
   * UUID of the inbox message
   */
  uuid: string;
  archiveRequest: components.ArchiveRequest;
};

/** @internal */
export const ArchiveInboxMessageRequest$inboundSchema: z.ZodType<
  ArchiveInboxMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  ArchiveRequest: components.ArchiveRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "ArchiveRequest": "archiveRequest",
  });
});

/** @internal */
export type ArchiveInboxMessageRequest$Outbound = {
  uuid: string;
  ArchiveRequest: components.ArchiveRequest$Outbound;
};

/** @internal */
export const ArchiveInboxMessageRequest$outboundSchema: z.ZodType<
  ArchiveInboxMessageRequest$Outbound,
  z.ZodTypeDef,
  ArchiveInboxMessageRequest
> = z.object({
  uuid: z.string(),
  archiveRequest: components.ArchiveRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    archiveRequest: "ArchiveRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArchiveInboxMessageRequest$ {
  /** @deprecated use `ArchiveInboxMessageRequest$inboundSchema` instead. */
  export const inboundSchema = ArchiveInboxMessageRequest$inboundSchema;
  /** @deprecated use `ArchiveInboxMessageRequest$outboundSchema` instead. */
  export const outboundSchema = ArchiveInboxMessageRequest$outboundSchema;
  /** @deprecated use `ArchiveInboxMessageRequest$Outbound` instead. */
  export type Outbound = ArchiveInboxMessageRequest$Outbound;
}

export function archiveInboxMessageRequestToJSON(
  archiveInboxMessageRequest: ArchiveInboxMessageRequest,
): string {
  return JSON.stringify(
    ArchiveInboxMessageRequest$outboundSchema.parse(archiveInboxMessageRequest),
  );
}

export function archiveInboxMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<ArchiveInboxMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArchiveInboxMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArchiveInboxMessageRequest' from JSON`,
  );
}
