/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateJobMaterialBundlesResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Result;
};

/** @internal */
export const CreateJobMaterialBundlesResponse$inboundSchema: z.ZodType<
  CreateJobMaterialBundlesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.Result$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateJobMaterialBundlesResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Result$Outbound;
};

/** @internal */
export const CreateJobMaterialBundlesResponse$outboundSchema: z.ZodType<
  CreateJobMaterialBundlesResponse$Outbound,
  z.ZodTypeDef,
  CreateJobMaterialBundlesResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.Result$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateJobMaterialBundlesResponse$ {
  /** @deprecated use `CreateJobMaterialBundlesResponse$inboundSchema` instead. */
  export const inboundSchema = CreateJobMaterialBundlesResponse$inboundSchema;
  /** @deprecated use `CreateJobMaterialBundlesResponse$outboundSchema` instead. */
  export const outboundSchema = CreateJobMaterialBundlesResponse$outboundSchema;
  /** @deprecated use `CreateJobMaterialBundlesResponse$Outbound` instead. */
  export type Outbound = CreateJobMaterialBundlesResponse$Outbound;
}

export function createJobMaterialBundlesResponseToJSON(
  createJobMaterialBundlesResponse: CreateJobMaterialBundlesResponse,
): string {
  return JSON.stringify(
    CreateJobMaterialBundlesResponse$outboundSchema.parse(
      createJobMaterialBundlesResponse,
    ),
  );
}

export function createJobMaterialBundlesResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateJobMaterialBundlesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateJobMaterialBundlesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateJobMaterialBundlesResponse' from JSON`,
  );
}
