/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateDocumentTemplatesResponseResult =
  | components.Result
  | components.ErrorT;

export type CreateDocumentTemplatesResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Result | components.ErrorT;
};

/** @internal */
export const CreateDocumentTemplatesResponseResult$inboundSchema: z.ZodType<
  CreateDocumentTemplatesResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type CreateDocumentTemplatesResponseResult$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const CreateDocumentTemplatesResponseResult$outboundSchema: z.ZodType<
  CreateDocumentTemplatesResponseResult$Outbound,
  z.ZodTypeDef,
  CreateDocumentTemplatesResponseResult
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDocumentTemplatesResponseResult$ {
  /** @deprecated use `CreateDocumentTemplatesResponseResult$inboundSchema` instead. */
  export const inboundSchema =
    CreateDocumentTemplatesResponseResult$inboundSchema;
  /** @deprecated use `CreateDocumentTemplatesResponseResult$outboundSchema` instead. */
  export const outboundSchema =
    CreateDocumentTemplatesResponseResult$outboundSchema;
  /** @deprecated use `CreateDocumentTemplatesResponseResult$Outbound` instead. */
  export type Outbound = CreateDocumentTemplatesResponseResult$Outbound;
}

export function createDocumentTemplatesResponseResultToJSON(
  createDocumentTemplatesResponseResult: CreateDocumentTemplatesResponseResult,
): string {
  return JSON.stringify(
    CreateDocumentTemplatesResponseResult$outboundSchema.parse(
      createDocumentTemplatesResponseResult,
    ),
  );
}

export function createDocumentTemplatesResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<CreateDocumentTemplatesResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateDocumentTemplatesResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDocumentTemplatesResponseResult' from JSON`,
  );
}

/** @internal */
export const CreateDocumentTemplatesResponse$inboundSchema: z.ZodType<
  CreateDocumentTemplatesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.union([
    components.Result$inboundSchema,
    components.ErrorT$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateDocumentTemplatesResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Result$Outbound | components.ErrorT$Outbound;
};

/** @internal */
export const CreateDocumentTemplatesResponse$outboundSchema: z.ZodType<
  CreateDocumentTemplatesResponse$Outbound,
  z.ZodTypeDef,
  CreateDocumentTemplatesResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.union([
    components.Result$outboundSchema,
    components.ErrorT$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDocumentTemplatesResponse$ {
  /** @deprecated use `CreateDocumentTemplatesResponse$inboundSchema` instead. */
  export const inboundSchema = CreateDocumentTemplatesResponse$inboundSchema;
  /** @deprecated use `CreateDocumentTemplatesResponse$outboundSchema` instead. */
  export const outboundSchema = CreateDocumentTemplatesResponse$outboundSchema;
  /** @deprecated use `CreateDocumentTemplatesResponse$Outbound` instead. */
  export type Outbound = CreateDocumentTemplatesResponse$Outbound;
}

export function createDocumentTemplatesResponseToJSON(
  createDocumentTemplatesResponse: CreateDocumentTemplatesResponse,
): string {
  return JSON.stringify(
    CreateDocumentTemplatesResponse$outboundSchema.parse(
      createDocumentTemplatesResponse,
    ),
  );
}

export function createDocumentTemplatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateDocumentTemplatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDocumentTemplatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDocumentTemplatesResponse' from JSON`,
  );
}
