/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateJobPaymentsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Result;
};

/** @internal */
export const CreateJobPaymentsResponse$inboundSchema: z.ZodType<
  CreateJobPaymentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.Result$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type CreateJobPaymentsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Result$Outbound;
};

/** @internal */
export const CreateJobPaymentsResponse$outboundSchema: z.ZodType<
  CreateJobPaymentsResponse$Outbound,
  z.ZodTypeDef,
  CreateJobPaymentsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.Result$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function createJobPaymentsResponseToJSON(
  createJobPaymentsResponse: CreateJobPaymentsResponse,
): string {
  return JSON.stringify(
    CreateJobPaymentsResponse$outboundSchema.parse(createJobPaymentsResponse),
  );
}
export function createJobPaymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateJobPaymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateJobPaymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateJobPaymentsResponse' from JSON`,
  );
}
