/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateFormFieldsResponseResult =
  | components.Result
  | components.ErrorT;

export type CreateFormFieldsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Result | components.ErrorT;
};

/** @internal */
export const CreateFormFieldsResponseResult$inboundSchema: z.ZodType<
  CreateFormFieldsResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type CreateFormFieldsResponseResult$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const CreateFormFieldsResponseResult$outboundSchema: z.ZodType<
  CreateFormFieldsResponseResult$Outbound,
  z.ZodTypeDef,
  CreateFormFieldsResponseResult
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateFormFieldsResponseResult$ {
  /** @deprecated use `CreateFormFieldsResponseResult$inboundSchema` instead. */
  export const inboundSchema = CreateFormFieldsResponseResult$inboundSchema;
  /** @deprecated use `CreateFormFieldsResponseResult$outboundSchema` instead. */
  export const outboundSchema = CreateFormFieldsResponseResult$outboundSchema;
  /** @deprecated use `CreateFormFieldsResponseResult$Outbound` instead. */
  export type Outbound = CreateFormFieldsResponseResult$Outbound;
}

export function createFormFieldsResponseResultToJSON(
  createFormFieldsResponseResult: CreateFormFieldsResponseResult,
): string {
  return JSON.stringify(
    CreateFormFieldsResponseResult$outboundSchema.parse(
      createFormFieldsResponseResult,
    ),
  );
}

export function createFormFieldsResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<CreateFormFieldsResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateFormFieldsResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateFormFieldsResponseResult' from JSON`,
  );
}

/** @internal */
export const CreateFormFieldsResponse$inboundSchema: z.ZodType<
  CreateFormFieldsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.union([
    components.Result$inboundSchema,
    components.ErrorT$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateFormFieldsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Result$Outbound | components.ErrorT$Outbound;
};

/** @internal */
export const CreateFormFieldsResponse$outboundSchema: z.ZodType<
  CreateFormFieldsResponse$Outbound,
  z.ZodTypeDef,
  CreateFormFieldsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.union([
    components.Result$outboundSchema,
    components.ErrorT$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateFormFieldsResponse$ {
  /** @deprecated use `CreateFormFieldsResponse$inboundSchema` instead. */
  export const inboundSchema = CreateFormFieldsResponse$inboundSchema;
  /** @deprecated use `CreateFormFieldsResponse$outboundSchema` instead. */
  export const outboundSchema = CreateFormFieldsResponse$outboundSchema;
  /** @deprecated use `CreateFormFieldsResponse$Outbound` instead. */
  export type Outbound = CreateFormFieldsResponse$Outbound;
}

export function createFormFieldsResponseToJSON(
  createFormFieldsResponse: CreateFormFieldsResponse,
): string {
  return JSON.stringify(
    CreateFormFieldsResponse$outboundSchema.parse(createFormFieldsResponse),
  );
}

export function createFormFieldsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateFormFieldsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateFormFieldsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateFormFieldsResponse' from JSON`,
  );
}
