/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateJobTemplatesResponseResult =
  | components.Result
  | components.ErrorT;

export type CreateJobTemplatesResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Result | components.ErrorT;
};

/** @internal */
export const CreateJobTemplatesResponseResult$inboundSchema: z.ZodType<
  CreateJobTemplatesResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type CreateJobTemplatesResponseResult$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const CreateJobTemplatesResponseResult$outboundSchema: z.ZodType<
  CreateJobTemplatesResponseResult$Outbound,
  z.ZodTypeDef,
  CreateJobTemplatesResponseResult
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateJobTemplatesResponseResult$ {
  /** @deprecated use `CreateJobTemplatesResponseResult$inboundSchema` instead. */
  export const inboundSchema = CreateJobTemplatesResponseResult$inboundSchema;
  /** @deprecated use `CreateJobTemplatesResponseResult$outboundSchema` instead. */
  export const outboundSchema = CreateJobTemplatesResponseResult$outboundSchema;
  /** @deprecated use `CreateJobTemplatesResponseResult$Outbound` instead. */
  export type Outbound = CreateJobTemplatesResponseResult$Outbound;
}

export function createJobTemplatesResponseResultToJSON(
  createJobTemplatesResponseResult: CreateJobTemplatesResponseResult,
): string {
  return JSON.stringify(
    CreateJobTemplatesResponseResult$outboundSchema.parse(
      createJobTemplatesResponseResult,
    ),
  );
}

export function createJobTemplatesResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<CreateJobTemplatesResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateJobTemplatesResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateJobTemplatesResponseResult' from JSON`,
  );
}

/** @internal */
export const CreateJobTemplatesResponse$inboundSchema: z.ZodType<
  CreateJobTemplatesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.union([
    components.Result$inboundSchema,
    components.ErrorT$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateJobTemplatesResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Result$Outbound | components.ErrorT$Outbound;
};

/** @internal */
export const CreateJobTemplatesResponse$outboundSchema: z.ZodType<
  CreateJobTemplatesResponse$Outbound,
  z.ZodTypeDef,
  CreateJobTemplatesResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.union([
    components.Result$outboundSchema,
    components.ErrorT$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateJobTemplatesResponse$ {
  /** @deprecated use `CreateJobTemplatesResponse$inboundSchema` instead. */
  export const inboundSchema = CreateJobTemplatesResponse$inboundSchema;
  /** @deprecated use `CreateJobTemplatesResponse$outboundSchema` instead. */
  export const outboundSchema = CreateJobTemplatesResponse$outboundSchema;
  /** @deprecated use `CreateJobTemplatesResponse$Outbound` instead. */
  export type Outbound = CreateJobTemplatesResponse$Outbound;
}

export function createJobTemplatesResponseToJSON(
  createJobTemplatesResponse: CreateJobTemplatesResponse,
): string {
  return JSON.stringify(
    CreateJobTemplatesResponse$outboundSchema.parse(createJobTemplatesResponse),
  );
}

export function createJobTemplatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateJobTemplatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateJobTemplatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateJobTemplatesResponse' from JSON`,
  );
}
