/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateAssetTypeFieldsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Result;
};

/** @internal */
export const CreateAssetTypeFieldsResponse$inboundSchema: z.ZodType<
  CreateAssetTypeFieldsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.Result$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type CreateAssetTypeFieldsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Result$Outbound;
};

/** @internal */
export const CreateAssetTypeFieldsResponse$outboundSchema: z.ZodType<
  CreateAssetTypeFieldsResponse$Outbound,
  z.ZodTypeDef,
  CreateAssetTypeFieldsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.Result$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function createAssetTypeFieldsResponseToJSON(
  createAssetTypeFieldsResponse: CreateAssetTypeFieldsResponse,
): string {
  return JSON.stringify(
    CreateAssetTypeFieldsResponse$outboundSchema.parse(
      createAssetTypeFieldsResponse,
    ),
  );
}
export function createAssetTypeFieldsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAssetTypeFieldsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAssetTypeFieldsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAssetTypeFieldsResponse' from JSON`,
  );
}
