/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateJobContactsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.Result;
};

/** @internal */
export const CreateJobContactsResponse$inboundSchema: z.ZodType<
  CreateJobContactsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.Result$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type CreateJobContactsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.Result$Outbound;
};

/** @internal */
export const CreateJobContactsResponse$outboundSchema: z.ZodType<
  CreateJobContactsResponse$Outbound,
  z.ZodTypeDef,
  CreateJobContactsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.Result$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function createJobContactsResponseToJSON(
  createJobContactsResponse: CreateJobContactsResponse,
): string {
  return JSON.stringify(
    CreateJobContactsResponse$outboundSchema.parse(createJobContactsResponse),
  );
}
export function createJobContactsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateJobContactsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateJobContactsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateJobContactsResponse' from JSON`,
  );
}
