/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteJobActivitiesRequest = {
  /**
   * UUID of the Job Activity
   */
  uuid: string;
};

/** @internal */
export const DeleteJobActivitiesRequest$inboundSchema: z.ZodType<
  DeleteJobActivitiesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});
/** @internal */
export type DeleteJobActivitiesRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteJobActivitiesRequest$outboundSchema: z.ZodType<
  DeleteJobActivitiesRequest$Outbound,
  z.ZodTypeDef,
  DeleteJobActivitiesRequest
> = z.object({
  uuid: z.string(),
});

export function deleteJobActivitiesRequestToJSON(
  deleteJobActivitiesRequest: DeleteJobActivitiesRequest,
): string {
  return JSON.stringify(
    DeleteJobActivitiesRequest$outboundSchema.parse(deleteJobActivitiesRequest),
  );
}
export function deleteJobActivitiesRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobActivitiesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobActivitiesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobActivitiesRequest' from JSON`,
  );
}
