/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteJobContactsSecurity = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

export type DeleteJobContactsRequest = {
  /**
   * UUID of the Job Contact
   */
  uuid: string;
};

export type DeleteJobContactsResponse = components.Result | components.ErrorT;

/** @internal */
export const DeleteJobContactsSecurity$inboundSchema: z.ZodType<
  DeleteJobContactsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/** @internal */
export type DeleteJobContactsSecurity$Outbound = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const DeleteJobContactsSecurity$outboundSchema: z.ZodType<
  DeleteJobContactsSecurity$Outbound,
  z.ZodTypeDef,
  DeleteJobContactsSecurity
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteJobContactsSecurity$ {
  /** @deprecated use `DeleteJobContactsSecurity$inboundSchema` instead. */
  export const inboundSchema = DeleteJobContactsSecurity$inboundSchema;
  /** @deprecated use `DeleteJobContactsSecurity$outboundSchema` instead. */
  export const outboundSchema = DeleteJobContactsSecurity$outboundSchema;
  /** @deprecated use `DeleteJobContactsSecurity$Outbound` instead. */
  export type Outbound = DeleteJobContactsSecurity$Outbound;
}

export function deleteJobContactsSecurityToJSON(
  deleteJobContactsSecurity: DeleteJobContactsSecurity,
): string {
  return JSON.stringify(
    DeleteJobContactsSecurity$outboundSchema.parse(deleteJobContactsSecurity),
  );
}

export function deleteJobContactsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobContactsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobContactsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobContactsSecurity' from JSON`,
  );
}

/** @internal */
export const DeleteJobContactsRequest$inboundSchema: z.ZodType<
  DeleteJobContactsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeleteJobContactsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteJobContactsRequest$outboundSchema: z.ZodType<
  DeleteJobContactsRequest$Outbound,
  z.ZodTypeDef,
  DeleteJobContactsRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteJobContactsRequest$ {
  /** @deprecated use `DeleteJobContactsRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteJobContactsRequest$inboundSchema;
  /** @deprecated use `DeleteJobContactsRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteJobContactsRequest$outboundSchema;
  /** @deprecated use `DeleteJobContactsRequest$Outbound` instead. */
  export type Outbound = DeleteJobContactsRequest$Outbound;
}

export function deleteJobContactsRequestToJSON(
  deleteJobContactsRequest: DeleteJobContactsRequest,
): string {
  return JSON.stringify(
    DeleteJobContactsRequest$outboundSchema.parse(deleteJobContactsRequest),
  );
}

export function deleteJobContactsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobContactsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobContactsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobContactsRequest' from JSON`,
  );
}

/** @internal */
export const DeleteJobContactsResponse$inboundSchema: z.ZodType<
  DeleteJobContactsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type DeleteJobContactsResponse$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const DeleteJobContactsResponse$outboundSchema: z.ZodType<
  DeleteJobContactsResponse$Outbound,
  z.ZodTypeDef,
  DeleteJobContactsResponse
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteJobContactsResponse$ {
  /** @deprecated use `DeleteJobContactsResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteJobContactsResponse$inboundSchema;
  /** @deprecated use `DeleteJobContactsResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteJobContactsResponse$outboundSchema;
  /** @deprecated use `DeleteJobContactsResponse$Outbound` instead. */
  export type Outbound = DeleteJobContactsResponse$Outbound;
}

export function deleteJobContactsResponseToJSON(
  deleteJobContactsResponse: DeleteJobContactsResponse,
): string {
  return JSON.stringify(
    DeleteJobContactsResponse$outboundSchema.parse(deleteJobContactsResponse),
  );
}

export function deleteJobContactsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobContactsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobContactsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobContactsResponse' from JSON`,
  );
}
