/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAssetsRequest = {
  /**
   * UUID of the Asset
   */
  uuid: string;
};

/** @internal */
export const DeleteAssetsRequest$inboundSchema: z.ZodType<
  DeleteAssetsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});
/** @internal */
export type DeleteAssetsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteAssetsRequest$outboundSchema: z.ZodType<
  DeleteAssetsRequest$Outbound,
  z.ZodTypeDef,
  DeleteAssetsRequest
> = z.object({
  uuid: z.string(),
});

export function deleteAssetsRequestToJSON(
  deleteAssetsRequest: DeleteAssetsRequest,
): string {
  return JSON.stringify(
    DeleteAssetsRequest$outboundSchema.parse(deleteAssetsRequest),
  );
}
export function deleteAssetsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAssetsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAssetsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAssetsRequest' from JSON`,
  );
}
