/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteClientsRequest = {
  /**
   * UUID of the Client
   */
  uuid: string;
};

/** @internal */
export const DeleteClientsRequest$inboundSchema: z.ZodType<
  DeleteClientsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeleteClientsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteClientsRequest$outboundSchema: z.ZodType<
  DeleteClientsRequest$Outbound,
  z.ZodTypeDef,
  DeleteClientsRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteClientsRequest$ {
  /** @deprecated use `DeleteClientsRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteClientsRequest$inboundSchema;
  /** @deprecated use `DeleteClientsRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteClientsRequest$outboundSchema;
  /** @deprecated use `DeleteClientsRequest$Outbound` instead. */
  export type Outbound = DeleteClientsRequest$Outbound;
}

export function deleteClientsRequestToJSON(
  deleteClientsRequest: DeleteClientsRequest,
): string {
  return JSON.stringify(
    DeleteClientsRequest$outboundSchema.parse(deleteClientsRequest),
  );
}

export function deleteClientsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteClientsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteClientsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteClientsRequest' from JSON`,
  );
}
