/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteKnowledgeArticlesSecurity = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

export type DeleteKnowledgeArticlesRequest = {
  /**
   * UUID of the Knowledge Article
   */
  uuid: string;
};

export type DeleteKnowledgeArticlesResponse =
  | components.Result
  | components.ErrorT;

/** @internal */
export const DeleteKnowledgeArticlesSecurity$inboundSchema: z.ZodType<
  DeleteKnowledgeArticlesSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/** @internal */
export type DeleteKnowledgeArticlesSecurity$Outbound = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const DeleteKnowledgeArticlesSecurity$outboundSchema: z.ZodType<
  DeleteKnowledgeArticlesSecurity$Outbound,
  z.ZodTypeDef,
  DeleteKnowledgeArticlesSecurity
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteKnowledgeArticlesSecurity$ {
  /** @deprecated use `DeleteKnowledgeArticlesSecurity$inboundSchema` instead. */
  export const inboundSchema = DeleteKnowledgeArticlesSecurity$inboundSchema;
  /** @deprecated use `DeleteKnowledgeArticlesSecurity$outboundSchema` instead. */
  export const outboundSchema = DeleteKnowledgeArticlesSecurity$outboundSchema;
  /** @deprecated use `DeleteKnowledgeArticlesSecurity$Outbound` instead. */
  export type Outbound = DeleteKnowledgeArticlesSecurity$Outbound;
}

export function deleteKnowledgeArticlesSecurityToJSON(
  deleteKnowledgeArticlesSecurity: DeleteKnowledgeArticlesSecurity,
): string {
  return JSON.stringify(
    DeleteKnowledgeArticlesSecurity$outboundSchema.parse(
      deleteKnowledgeArticlesSecurity,
    ),
  );
}

export function deleteKnowledgeArticlesSecurityFromJSON(
  jsonString: string,
): SafeParseResult<DeleteKnowledgeArticlesSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteKnowledgeArticlesSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteKnowledgeArticlesSecurity' from JSON`,
  );
}

/** @internal */
export const DeleteKnowledgeArticlesRequest$inboundSchema: z.ZodType<
  DeleteKnowledgeArticlesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeleteKnowledgeArticlesRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteKnowledgeArticlesRequest$outboundSchema: z.ZodType<
  DeleteKnowledgeArticlesRequest$Outbound,
  z.ZodTypeDef,
  DeleteKnowledgeArticlesRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteKnowledgeArticlesRequest$ {
  /** @deprecated use `DeleteKnowledgeArticlesRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteKnowledgeArticlesRequest$inboundSchema;
  /** @deprecated use `DeleteKnowledgeArticlesRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteKnowledgeArticlesRequest$outboundSchema;
  /** @deprecated use `DeleteKnowledgeArticlesRequest$Outbound` instead. */
  export type Outbound = DeleteKnowledgeArticlesRequest$Outbound;
}

export function deleteKnowledgeArticlesRequestToJSON(
  deleteKnowledgeArticlesRequest: DeleteKnowledgeArticlesRequest,
): string {
  return JSON.stringify(
    DeleteKnowledgeArticlesRequest$outboundSchema.parse(
      deleteKnowledgeArticlesRequest,
    ),
  );
}

export function deleteKnowledgeArticlesRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteKnowledgeArticlesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteKnowledgeArticlesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteKnowledgeArticlesRequest' from JSON`,
  );
}

/** @internal */
export const DeleteKnowledgeArticlesResponse$inboundSchema: z.ZodType<
  DeleteKnowledgeArticlesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type DeleteKnowledgeArticlesResponse$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const DeleteKnowledgeArticlesResponse$outboundSchema: z.ZodType<
  DeleteKnowledgeArticlesResponse$Outbound,
  z.ZodTypeDef,
  DeleteKnowledgeArticlesResponse
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteKnowledgeArticlesResponse$ {
  /** @deprecated use `DeleteKnowledgeArticlesResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteKnowledgeArticlesResponse$inboundSchema;
  /** @deprecated use `DeleteKnowledgeArticlesResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteKnowledgeArticlesResponse$outboundSchema;
  /** @deprecated use `DeleteKnowledgeArticlesResponse$Outbound` instead. */
  export type Outbound = DeleteKnowledgeArticlesResponse$Outbound;
}

export function deleteKnowledgeArticlesResponseToJSON(
  deleteKnowledgeArticlesResponse: DeleteKnowledgeArticlesResponse,
): string {
  return JSON.stringify(
    DeleteKnowledgeArticlesResponse$outboundSchema.parse(
      deleteKnowledgeArticlesResponse,
    ),
  );
}

export function deleteKnowledgeArticlesResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteKnowledgeArticlesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteKnowledgeArticlesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteKnowledgeArticlesResponse' from JSON`,
  );
}
