/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteJobMaterialBundlesRequest = {
  /**
   * UUID of the Job Material Bundle
   */
  uuid: string;
};

/** @internal */
export const DeleteJobMaterialBundlesRequest$inboundSchema: z.ZodType<
  DeleteJobMaterialBundlesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeleteJobMaterialBundlesRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteJobMaterialBundlesRequest$outboundSchema: z.ZodType<
  DeleteJobMaterialBundlesRequest$Outbound,
  z.ZodTypeDef,
  DeleteJobMaterialBundlesRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteJobMaterialBundlesRequest$ {
  /** @deprecated use `DeleteJobMaterialBundlesRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteJobMaterialBundlesRequest$inboundSchema;
  /** @deprecated use `DeleteJobMaterialBundlesRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteJobMaterialBundlesRequest$outboundSchema;
  /** @deprecated use `DeleteJobMaterialBundlesRequest$Outbound` instead. */
  export type Outbound = DeleteJobMaterialBundlesRequest$Outbound;
}

export function deleteJobMaterialBundlesRequestToJSON(
  deleteJobMaterialBundlesRequest: DeleteJobMaterialBundlesRequest,
): string {
  return JSON.stringify(
    DeleteJobMaterialBundlesRequest$outboundSchema.parse(
      deleteJobMaterialBundlesRequest,
    ),
  );
}

export function deleteJobMaterialBundlesRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobMaterialBundlesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobMaterialBundlesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobMaterialBundlesRequest' from JSON`,
  );
}
