/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteTasksRequest = {
  /**
   * UUID of the Task
   */
  uuid: string;
};

/** @internal */
export const DeleteTasksRequest$inboundSchema: z.ZodType<
  DeleteTasksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeleteTasksRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteTasksRequest$outboundSchema: z.ZodType<
  DeleteTasksRequest$Outbound,
  z.ZodTypeDef,
  DeleteTasksRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteTasksRequest$ {
  /** @deprecated use `DeleteTasksRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteTasksRequest$inboundSchema;
  /** @deprecated use `DeleteTasksRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteTasksRequest$outboundSchema;
  /** @deprecated use `DeleteTasksRequest$Outbound` instead. */
  export type Outbound = DeleteTasksRequest$Outbound;
}

export function deleteTasksRequestToJSON(
  deleteTasksRequest: DeleteTasksRequest,
): string {
  return JSON.stringify(
    DeleteTasksRequest$outboundSchema.parse(deleteTasksRequest),
  );
}

export function deleteTasksRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTasksRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteTasksRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTasksRequest' from JSON`,
  );
}
