/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteJobMaterialsSecurity = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

export type DeleteJobMaterialsRequest = {
  /**
   * UUID of the Job Material
   */
  uuid: string;
};

export type DeleteJobMaterialsResponse = components.Result | components.ErrorT;

/** @internal */
export const DeleteJobMaterialsSecurity$inboundSchema: z.ZodType<
  DeleteJobMaterialsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/** @internal */
export type DeleteJobMaterialsSecurity$Outbound = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const DeleteJobMaterialsSecurity$outboundSchema: z.ZodType<
  DeleteJobMaterialsSecurity$Outbound,
  z.ZodTypeDef,
  DeleteJobMaterialsSecurity
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteJobMaterialsSecurity$ {
  /** @deprecated use `DeleteJobMaterialsSecurity$inboundSchema` instead. */
  export const inboundSchema = DeleteJobMaterialsSecurity$inboundSchema;
  /** @deprecated use `DeleteJobMaterialsSecurity$outboundSchema` instead. */
  export const outboundSchema = DeleteJobMaterialsSecurity$outboundSchema;
  /** @deprecated use `DeleteJobMaterialsSecurity$Outbound` instead. */
  export type Outbound = DeleteJobMaterialsSecurity$Outbound;
}

export function deleteJobMaterialsSecurityToJSON(
  deleteJobMaterialsSecurity: DeleteJobMaterialsSecurity,
): string {
  return JSON.stringify(
    DeleteJobMaterialsSecurity$outboundSchema.parse(deleteJobMaterialsSecurity),
  );
}

export function deleteJobMaterialsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobMaterialsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobMaterialsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobMaterialsSecurity' from JSON`,
  );
}

/** @internal */
export const DeleteJobMaterialsRequest$inboundSchema: z.ZodType<
  DeleteJobMaterialsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeleteJobMaterialsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteJobMaterialsRequest$outboundSchema: z.ZodType<
  DeleteJobMaterialsRequest$Outbound,
  z.ZodTypeDef,
  DeleteJobMaterialsRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteJobMaterialsRequest$ {
  /** @deprecated use `DeleteJobMaterialsRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteJobMaterialsRequest$inboundSchema;
  /** @deprecated use `DeleteJobMaterialsRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteJobMaterialsRequest$outboundSchema;
  /** @deprecated use `DeleteJobMaterialsRequest$Outbound` instead. */
  export type Outbound = DeleteJobMaterialsRequest$Outbound;
}

export function deleteJobMaterialsRequestToJSON(
  deleteJobMaterialsRequest: DeleteJobMaterialsRequest,
): string {
  return JSON.stringify(
    DeleteJobMaterialsRequest$outboundSchema.parse(deleteJobMaterialsRequest),
  );
}

export function deleteJobMaterialsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobMaterialsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobMaterialsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobMaterialsRequest' from JSON`,
  );
}

/** @internal */
export const DeleteJobMaterialsResponse$inboundSchema: z.ZodType<
  DeleteJobMaterialsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type DeleteJobMaterialsResponse$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const DeleteJobMaterialsResponse$outboundSchema: z.ZodType<
  DeleteJobMaterialsResponse$Outbound,
  z.ZodTypeDef,
  DeleteJobMaterialsResponse
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteJobMaterialsResponse$ {
  /** @deprecated use `DeleteJobMaterialsResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteJobMaterialsResponse$inboundSchema;
  /** @deprecated use `DeleteJobMaterialsResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteJobMaterialsResponse$outboundSchema;
  /** @deprecated use `DeleteJobMaterialsResponse$Outbound` instead. */
  export type Outbound = DeleteJobMaterialsResponse$Outbound;
}

export function deleteJobMaterialsResponseToJSON(
  deleteJobMaterialsResponse: DeleteJobMaterialsResponse,
): string {
  return JSON.stringify(
    DeleteJobMaterialsResponse$outboundSchema.parse(deleteJobMaterialsResponse),
  );
}

export function deleteJobMaterialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteJobMaterialsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteJobMaterialsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteJobMaterialsResponse' from JSON`,
  );
}
