/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAllocationWindowsSecurity = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

export type DeleteAllocationWindowsRequest = {
  /**
   * UUID of the Allocation Window
   */
  uuid: string;
};

export type DeleteAllocationWindowsResponse =
  | components.Result
  | components.ErrorT;

/** @internal */
export const DeleteAllocationWindowsSecurity$inboundSchema: z.ZodType<
  DeleteAllocationWindowsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/** @internal */
export type DeleteAllocationWindowsSecurity$Outbound = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const DeleteAllocationWindowsSecurity$outboundSchema: z.ZodType<
  DeleteAllocationWindowsSecurity$Outbound,
  z.ZodTypeDef,
  DeleteAllocationWindowsSecurity
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAllocationWindowsSecurity$ {
  /** @deprecated use `DeleteAllocationWindowsSecurity$inboundSchema` instead. */
  export const inboundSchema = DeleteAllocationWindowsSecurity$inboundSchema;
  /** @deprecated use `DeleteAllocationWindowsSecurity$outboundSchema` instead. */
  export const outboundSchema = DeleteAllocationWindowsSecurity$outboundSchema;
  /** @deprecated use `DeleteAllocationWindowsSecurity$Outbound` instead. */
  export type Outbound = DeleteAllocationWindowsSecurity$Outbound;
}

export function deleteAllocationWindowsSecurityToJSON(
  deleteAllocationWindowsSecurity: DeleteAllocationWindowsSecurity,
): string {
  return JSON.stringify(
    DeleteAllocationWindowsSecurity$outboundSchema.parse(
      deleteAllocationWindowsSecurity,
    ),
  );
}

export function deleteAllocationWindowsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAllocationWindowsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAllocationWindowsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAllocationWindowsSecurity' from JSON`,
  );
}

/** @internal */
export const DeleteAllocationWindowsRequest$inboundSchema: z.ZodType<
  DeleteAllocationWindowsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type DeleteAllocationWindowsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const DeleteAllocationWindowsRequest$outboundSchema: z.ZodType<
  DeleteAllocationWindowsRequest$Outbound,
  z.ZodTypeDef,
  DeleteAllocationWindowsRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAllocationWindowsRequest$ {
  /** @deprecated use `DeleteAllocationWindowsRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteAllocationWindowsRequest$inboundSchema;
  /** @deprecated use `DeleteAllocationWindowsRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteAllocationWindowsRequest$outboundSchema;
  /** @deprecated use `DeleteAllocationWindowsRequest$Outbound` instead. */
  export type Outbound = DeleteAllocationWindowsRequest$Outbound;
}

export function deleteAllocationWindowsRequestToJSON(
  deleteAllocationWindowsRequest: DeleteAllocationWindowsRequest,
): string {
  return JSON.stringify(
    DeleteAllocationWindowsRequest$outboundSchema.parse(
      deleteAllocationWindowsRequest,
    ),
  );
}

export function deleteAllocationWindowsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAllocationWindowsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAllocationWindowsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAllocationWindowsRequest' from JSON`,
  );
}

/** @internal */
export const DeleteAllocationWindowsResponse$inboundSchema: z.ZodType<
  DeleteAllocationWindowsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type DeleteAllocationWindowsResponse$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const DeleteAllocationWindowsResponse$outboundSchema: z.ZodType<
  DeleteAllocationWindowsResponse$Outbound,
  z.ZodTypeDef,
  DeleteAllocationWindowsResponse
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAllocationWindowsResponse$ {
  /** @deprecated use `DeleteAllocationWindowsResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteAllocationWindowsResponse$inboundSchema;
  /** @deprecated use `DeleteAllocationWindowsResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteAllocationWindowsResponse$outboundSchema;
  /** @deprecated use `DeleteAllocationWindowsResponse$Outbound` instead. */
  export type Outbound = DeleteAllocationWindowsResponse$Outbound;
}

export function deleteAllocationWindowsResponseToJSON(
  deleteAllocationWindowsResponse: DeleteAllocationWindowsResponse,
): string {
  return JSON.stringify(
    DeleteAllocationWindowsResponse$outboundSchema.parse(
      deleteAllocationWindowsResponse,
    ),
  );
}

export function deleteAllocationWindowsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAllocationWindowsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAllocationWindowsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAllocationWindowsResponse' from JSON`,
  );
}
