/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetClientsRequest = {
  /**
   * UUID of the Client
   */
  uuid: string;
};

/** @internal */
export const GetClientsRequest$inboundSchema: z.ZodType<
  GetClientsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});
/** @internal */
export type GetClientsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetClientsRequest$outboundSchema: z.ZodType<
  GetClientsRequest$Outbound,
  z.ZodTypeDef,
  GetClientsRequest
> = z.object({
  uuid: z.string(),
});

export function getClientsRequestToJSON(
  getClientsRequest: GetClientsRequest,
): string {
  return JSON.stringify(
    GetClientsRequest$outboundSchema.parse(getClientsRequest),
  );
}
export function getClientsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetClientsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClientsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientsRequest' from JSON`,
  );
}
