/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetJobMaterialsSecurity = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

export type GetJobMaterialsRequest = {
  /**
   * UUID of the Job Material
   */
  uuid: string;
};

export type GetJobMaterialsResponse =
  | components.ErrorT
  | components.JobMaterial;

/** @internal */
export const GetJobMaterialsSecurity$inboundSchema: z.ZodType<
  GetJobMaterialsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/** @internal */
export type GetJobMaterialsSecurity$Outbound = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const GetJobMaterialsSecurity$outboundSchema: z.ZodType<
  GetJobMaterialsSecurity$Outbound,
  z.ZodTypeDef,
  GetJobMaterialsSecurity
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobMaterialsSecurity$ {
  /** @deprecated use `GetJobMaterialsSecurity$inboundSchema` instead. */
  export const inboundSchema = GetJobMaterialsSecurity$inboundSchema;
  /** @deprecated use `GetJobMaterialsSecurity$outboundSchema` instead. */
  export const outboundSchema = GetJobMaterialsSecurity$outboundSchema;
  /** @deprecated use `GetJobMaterialsSecurity$Outbound` instead. */
  export type Outbound = GetJobMaterialsSecurity$Outbound;
}

export function getJobMaterialsSecurityToJSON(
  getJobMaterialsSecurity: GetJobMaterialsSecurity,
): string {
  return JSON.stringify(
    GetJobMaterialsSecurity$outboundSchema.parse(getJobMaterialsSecurity),
  );
}

export function getJobMaterialsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetJobMaterialsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetJobMaterialsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetJobMaterialsSecurity' from JSON`,
  );
}

/** @internal */
export const GetJobMaterialsRequest$inboundSchema: z.ZodType<
  GetJobMaterialsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetJobMaterialsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetJobMaterialsRequest$outboundSchema: z.ZodType<
  GetJobMaterialsRequest$Outbound,
  z.ZodTypeDef,
  GetJobMaterialsRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobMaterialsRequest$ {
  /** @deprecated use `GetJobMaterialsRequest$inboundSchema` instead. */
  export const inboundSchema = GetJobMaterialsRequest$inboundSchema;
  /** @deprecated use `GetJobMaterialsRequest$outboundSchema` instead. */
  export const outboundSchema = GetJobMaterialsRequest$outboundSchema;
  /** @deprecated use `GetJobMaterialsRequest$Outbound` instead. */
  export type Outbound = GetJobMaterialsRequest$Outbound;
}

export function getJobMaterialsRequestToJSON(
  getJobMaterialsRequest: GetJobMaterialsRequest,
): string {
  return JSON.stringify(
    GetJobMaterialsRequest$outboundSchema.parse(getJobMaterialsRequest),
  );
}

export function getJobMaterialsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetJobMaterialsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetJobMaterialsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetJobMaterialsRequest' from JSON`,
  );
}

/** @internal */
export const GetJobMaterialsResponse$inboundSchema: z.ZodType<
  GetJobMaterialsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.ErrorT$inboundSchema,
  components.JobMaterial$inboundSchema,
]);

/** @internal */
export type GetJobMaterialsResponse$Outbound =
  | components.ErrorT$Outbound
  | components.JobMaterial$Outbound;

/** @internal */
export const GetJobMaterialsResponse$outboundSchema: z.ZodType<
  GetJobMaterialsResponse$Outbound,
  z.ZodTypeDef,
  GetJobMaterialsResponse
> = z.union([
  components.ErrorT$outboundSchema,
  components.JobMaterial$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobMaterialsResponse$ {
  /** @deprecated use `GetJobMaterialsResponse$inboundSchema` instead. */
  export const inboundSchema = GetJobMaterialsResponse$inboundSchema;
  /** @deprecated use `GetJobMaterialsResponse$outboundSchema` instead. */
  export const outboundSchema = GetJobMaterialsResponse$outboundSchema;
  /** @deprecated use `GetJobMaterialsResponse$Outbound` instead. */
  export type Outbound = GetJobMaterialsResponse$Outbound;
}

export function getJobMaterialsResponseToJSON(
  getJobMaterialsResponse: GetJobMaterialsResponse,
): string {
  return JSON.stringify(
    GetJobMaterialsResponse$outboundSchema.parse(getJobMaterialsResponse),
  );
}

export function getJobMaterialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetJobMaterialsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetJobMaterialsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetJobMaterialsResponse' from JSON`,
  );
}
