/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetLocationsRequest = {
  /**
   * UUID of the Location
   */
  uuid: string;
};

/** @internal */
export const GetLocationsRequest$inboundSchema: z.ZodType<
  GetLocationsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});
/** @internal */
export type GetLocationsRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetLocationsRequest$outboundSchema: z.ZodType<
  GetLocationsRequest$Outbound,
  z.ZodTypeDef,
  GetLocationsRequest
> = z.object({
  uuid: z.string(),
});

export function getLocationsRequestToJSON(
  getLocationsRequest: GetLocationsRequest,
): string {
  return JSON.stringify(
    GetLocationsRequest$outboundSchema.parse(getLocationsRequest),
  );
}
export function getLocationsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetLocationsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLocationsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLocationsRequest' from JSON`,
  );
}
