/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetStaffMembersRequest = {
  /**
   * UUID of the Staff Member
   */
  uuid: string;
};

/** @internal */
export const GetStaffMembersRequest$inboundSchema: z.ZodType<
  GetStaffMembersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetStaffMembersRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetStaffMembersRequest$outboundSchema: z.ZodType<
  GetStaffMembersRequest$Outbound,
  z.ZodTypeDef,
  GetStaffMembersRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetStaffMembersRequest$ {
  /** @deprecated use `GetStaffMembersRequest$inboundSchema` instead. */
  export const inboundSchema = GetStaffMembersRequest$inboundSchema;
  /** @deprecated use `GetStaffMembersRequest$outboundSchema` instead. */
  export const outboundSchema = GetStaffMembersRequest$outboundSchema;
  /** @deprecated use `GetStaffMembersRequest$Outbound` instead. */
  export type Outbound = GetStaffMembersRequest$Outbound;
}

export function getStaffMembersRequestToJSON(
  getStaffMembersRequest: GetStaffMembersRequest,
): string {
  return JSON.stringify(
    GetStaffMembersRequest$outboundSchema.parse(getStaffMembersRequest),
  );
}

export function getStaffMembersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetStaffMembersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStaffMembersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStaffMembersRequest' from JSON`,
  );
}
