/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSuppliersRequest = {
  /**
   * UUID of the Supplier
   */
  uuid: string;
};

/** @internal */
export const GetSuppliersRequest$inboundSchema: z.ZodType<
  GetSuppliersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});

/** @internal */
export type GetSuppliersRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetSuppliersRequest$outboundSchema: z.ZodType<
  GetSuppliersRequest$Outbound,
  z.ZodTypeDef,
  GetSuppliersRequest
> = z.object({
  uuid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSuppliersRequest$ {
  /** @deprecated use `GetSuppliersRequest$inboundSchema` instead. */
  export const inboundSchema = GetSuppliersRequest$inboundSchema;
  /** @deprecated use `GetSuppliersRequest$outboundSchema` instead. */
  export const outboundSchema = GetSuppliersRequest$outboundSchema;
  /** @deprecated use `GetSuppliersRequest$Outbound` instead. */
  export type Outbound = GetSuppliersRequest$Outbound;
}

export function getSuppliersRequestToJSON(
  getSuppliersRequest: GetSuppliersRequest,
): string {
  return JSON.stringify(
    GetSuppliersRequest$outboundSchema.parse(getSuppliersRequest),
  );
}

export function getSuppliersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSuppliersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSuppliersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSuppliersRequest' from JSON`,
  );
}
