/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTasksRequest = {
  /**
   * UUID of the Task
   */
  uuid: string;
};

/** @internal */
export const GetTasksRequest$inboundSchema: z.ZodType<
  GetTasksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
});
/** @internal */
export type GetTasksRequest$Outbound = {
  uuid: string;
};

/** @internal */
export const GetTasksRequest$outboundSchema: z.ZodType<
  GetTasksRequest$Outbound,
  z.ZodTypeDef,
  GetTasksRequest
> = z.object({
  uuid: z.string(),
});

export function getTasksRequestToJSON(
  getTasksRequest: GetTasksRequest,
): string {
  return JSON.stringify(GetTasksRequest$outboundSchema.parse(getTasksRequest));
}
export function getTasksRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTasksRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTasksRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTasksRequest' from JSON`,
  );
}
