/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListFeedbackResponse =
  | components.ErrorT
  | Array<components.Feedback>;

/** @internal */
export const ListFeedbackResponse$inboundSchema: z.ZodType<
  ListFeedbackResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.ErrorT$inboundSchema,
  z.array(components.Feedback$inboundSchema),
]);

/** @internal */
export type ListFeedbackResponse$Outbound =
  | components.ErrorT$Outbound
  | Array<components.Feedback$Outbound>;

/** @internal */
export const ListFeedbackResponse$outboundSchema: z.ZodType<
  ListFeedbackResponse$Outbound,
  z.ZodTypeDef,
  ListFeedbackResponse
> = z.union([
  components.ErrorT$outboundSchema,
  z.array(components.Feedback$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListFeedbackResponse$ {
  /** @deprecated use `ListFeedbackResponse$inboundSchema` instead. */
  export const inboundSchema = ListFeedbackResponse$inboundSchema;
  /** @deprecated use `ListFeedbackResponse$outboundSchema` instead. */
  export const outboundSchema = ListFeedbackResponse$outboundSchema;
  /** @deprecated use `ListFeedbackResponse$Outbound` instead. */
  export type Outbound = ListFeedbackResponse$Outbound;
}

export function listFeedbackResponseToJSON(
  listFeedbackResponse: ListFeedbackResponse,
): string {
  return JSON.stringify(
    ListFeedbackResponse$outboundSchema.parse(listFeedbackResponse),
  );
}

export function listFeedbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListFeedbackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFeedbackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFeedbackResponse' from JSON`,
  );
}
