/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListJobChecklistsResponse =
  | components.ErrorT
  | Array<components.JobChecklist>;

/** @internal */
export const ListJobChecklistsResponse$inboundSchema: z.ZodType<
  ListJobChecklistsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.ErrorT$inboundSchema,
  z.array(components.JobChecklist$inboundSchema),
]);

/** @internal */
export type ListJobChecklistsResponse$Outbound =
  | components.ErrorT$Outbound
  | Array<components.JobChecklist$Outbound>;

/** @internal */
export const ListJobChecklistsResponse$outboundSchema: z.ZodType<
  ListJobChecklistsResponse$Outbound,
  z.ZodTypeDef,
  ListJobChecklistsResponse
> = z.union([
  components.ErrorT$outboundSchema,
  z.array(components.JobChecklist$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListJobChecklistsResponse$ {
  /** @deprecated use `ListJobChecklistsResponse$inboundSchema` instead. */
  export const inboundSchema = ListJobChecklistsResponse$inboundSchema;
  /** @deprecated use `ListJobChecklistsResponse$outboundSchema` instead. */
  export const outboundSchema = ListJobChecklistsResponse$outboundSchema;
  /** @deprecated use `ListJobChecklistsResponse$Outbound` instead. */
  export type Outbound = ListJobChecklistsResponse$Outbound;
}

export function listJobChecklistsResponseToJSON(
  listJobChecklistsResponse: ListJobChecklistsResponse,
): string {
  return JSON.stringify(
    ListJobChecklistsResponse$outboundSchema.parse(listJobChecklistsResponse),
  );
}

export function listJobChecklistsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListJobChecklistsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListJobChecklistsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListJobChecklistsResponse' from JSON`,
  );
}
