/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateJobAllocationsRequest = {
  /**
   * UUID of the Job Allocation
   */
  uuid: string;
  /**
   * Job Allocation fields to update
   */
  jobAllocationCreate: components.JobAllocationCreate;
};

/** @internal */
export const UpdateJobAllocationsRequest$inboundSchema: z.ZodType<
  UpdateJobAllocationsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  JobAllocationCreate: components.JobAllocationCreate$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "JobAllocationCreate": "jobAllocationCreate",
  });
});

/** @internal */
export type UpdateJobAllocationsRequest$Outbound = {
  uuid: string;
  JobAllocationCreate: components.JobAllocationCreate$Outbound;
};

/** @internal */
export const UpdateJobAllocationsRequest$outboundSchema: z.ZodType<
  UpdateJobAllocationsRequest$Outbound,
  z.ZodTypeDef,
  UpdateJobAllocationsRequest
> = z.object({
  uuid: z.string(),
  jobAllocationCreate: components.JobAllocationCreate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    jobAllocationCreate: "JobAllocationCreate",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateJobAllocationsRequest$ {
  /** @deprecated use `UpdateJobAllocationsRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateJobAllocationsRequest$inboundSchema;
  /** @deprecated use `UpdateJobAllocationsRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateJobAllocationsRequest$outboundSchema;
  /** @deprecated use `UpdateJobAllocationsRequest$Outbound` instead. */
  export type Outbound = UpdateJobAllocationsRequest$Outbound;
}

export function updateJobAllocationsRequestToJSON(
  updateJobAllocationsRequest: UpdateJobAllocationsRequest,
): string {
  return JSON.stringify(
    UpdateJobAllocationsRequest$outboundSchema.parse(
      updateJobAllocationsRequest,
    ),
  );
}

export function updateJobAllocationsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateJobAllocationsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateJobAllocationsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateJobAllocationsRequest' from JSON`,
  );
}
