/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateCompanyContactsRequest = {
  /**
   * UUID of the Company Contact
   */
  uuid: string;
  /**
   * Company Contact fields to update
   */
  companyContactCreate: components.CompanyContactCreate;
};

/** @internal */
export const UpdateCompanyContactsRequest$inboundSchema: z.ZodType<
  UpdateCompanyContactsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  CompanyContactCreate: components.CompanyContactCreate$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "CompanyContactCreate": "companyContactCreate",
  });
});

/** @internal */
export type UpdateCompanyContactsRequest$Outbound = {
  uuid: string;
  CompanyContactCreate: components.CompanyContactCreate$Outbound;
};

/** @internal */
export const UpdateCompanyContactsRequest$outboundSchema: z.ZodType<
  UpdateCompanyContactsRequest$Outbound,
  z.ZodTypeDef,
  UpdateCompanyContactsRequest
> = z.object({
  uuid: z.string(),
  companyContactCreate: components.CompanyContactCreate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    companyContactCreate: "CompanyContactCreate",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCompanyContactsRequest$ {
  /** @deprecated use `UpdateCompanyContactsRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCompanyContactsRequest$inboundSchema;
  /** @deprecated use `UpdateCompanyContactsRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCompanyContactsRequest$outboundSchema;
  /** @deprecated use `UpdateCompanyContactsRequest$Outbound` instead. */
  export type Outbound = UpdateCompanyContactsRequest$Outbound;
}

export function updateCompanyContactsRequestToJSON(
  updateCompanyContactsRequest: UpdateCompanyContactsRequest,
): string {
  return JSON.stringify(
    UpdateCompanyContactsRequest$outboundSchema.parse(
      updateCompanyContactsRequest,
    ),
  );
}

export function updateCompanyContactsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCompanyContactsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCompanyContactsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCompanyContactsRequest' from JSON`,
  );
}
