/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateAllocationWindowsSecurity = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

export type UpdateAllocationWindowsRequest = {
  /**
   * UUID of the Allocation Window
   */
  uuid: string;
  /**
   * Allocation Window fields to update
   */
  allocationWindow: components.AllocationWindowInput;
};

export type UpdateAllocationWindowsResponse =
  | components.Result
  | components.ErrorT;

/** @internal */
export const UpdateAllocationWindowsSecurity$inboundSchema: z.ZodType<
  UpdateAllocationWindowsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/** @internal */
export type UpdateAllocationWindowsSecurity$Outbound = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const UpdateAllocationWindowsSecurity$outboundSchema: z.ZodType<
  UpdateAllocationWindowsSecurity$Outbound,
  z.ZodTypeDef,
  UpdateAllocationWindowsSecurity
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAllocationWindowsSecurity$ {
  /** @deprecated use `UpdateAllocationWindowsSecurity$inboundSchema` instead. */
  export const inboundSchema = UpdateAllocationWindowsSecurity$inboundSchema;
  /** @deprecated use `UpdateAllocationWindowsSecurity$outboundSchema` instead. */
  export const outboundSchema = UpdateAllocationWindowsSecurity$outboundSchema;
  /** @deprecated use `UpdateAllocationWindowsSecurity$Outbound` instead. */
  export type Outbound = UpdateAllocationWindowsSecurity$Outbound;
}

export function updateAllocationWindowsSecurityToJSON(
  updateAllocationWindowsSecurity: UpdateAllocationWindowsSecurity,
): string {
  return JSON.stringify(
    UpdateAllocationWindowsSecurity$outboundSchema.parse(
      updateAllocationWindowsSecurity,
    ),
  );
}

export function updateAllocationWindowsSecurityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAllocationWindowsSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAllocationWindowsSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAllocationWindowsSecurity' from JSON`,
  );
}

/** @internal */
export const UpdateAllocationWindowsRequest$inboundSchema: z.ZodType<
  UpdateAllocationWindowsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  AllocationWindow: components.AllocationWindowInput$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "AllocationWindow": "allocationWindow",
  });
});

/** @internal */
export type UpdateAllocationWindowsRequest$Outbound = {
  uuid: string;
  AllocationWindow: components.AllocationWindowInput$Outbound;
};

/** @internal */
export const UpdateAllocationWindowsRequest$outboundSchema: z.ZodType<
  UpdateAllocationWindowsRequest$Outbound,
  z.ZodTypeDef,
  UpdateAllocationWindowsRequest
> = z.object({
  uuid: z.string(),
  allocationWindow: components.AllocationWindowInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    allocationWindow: "AllocationWindow",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAllocationWindowsRequest$ {
  /** @deprecated use `UpdateAllocationWindowsRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateAllocationWindowsRequest$inboundSchema;
  /** @deprecated use `UpdateAllocationWindowsRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateAllocationWindowsRequest$outboundSchema;
  /** @deprecated use `UpdateAllocationWindowsRequest$Outbound` instead. */
  export type Outbound = UpdateAllocationWindowsRequest$Outbound;
}

export function updateAllocationWindowsRequestToJSON(
  updateAllocationWindowsRequest: UpdateAllocationWindowsRequest,
): string {
  return JSON.stringify(
    UpdateAllocationWindowsRequest$outboundSchema.parse(
      updateAllocationWindowsRequest,
    ),
  );
}

export function updateAllocationWindowsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAllocationWindowsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAllocationWindowsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAllocationWindowsRequest' from JSON`,
  );
}

/** @internal */
export const UpdateAllocationWindowsResponse$inboundSchema: z.ZodType<
  UpdateAllocationWindowsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type UpdateAllocationWindowsResponse$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const UpdateAllocationWindowsResponse$outboundSchema: z.ZodType<
  UpdateAllocationWindowsResponse$Outbound,
  z.ZodTypeDef,
  UpdateAllocationWindowsResponse
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAllocationWindowsResponse$ {
  /** @deprecated use `UpdateAllocationWindowsResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateAllocationWindowsResponse$inboundSchema;
  /** @deprecated use `UpdateAllocationWindowsResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateAllocationWindowsResponse$outboundSchema;
  /** @deprecated use `UpdateAllocationWindowsResponse$Outbound` instead. */
  export type Outbound = UpdateAllocationWindowsResponse$Outbound;
}

export function updateAllocationWindowsResponseToJSON(
  updateAllocationWindowsResponse: UpdateAllocationWindowsResponse,
): string {
  return JSON.stringify(
    UpdateAllocationWindowsResponse$outboundSchema.parse(
      updateAllocationWindowsResponse,
    ),
  );
}

export function updateAllocationWindowsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAllocationWindowsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAllocationWindowsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAllocationWindowsResponse' from JSON`,
  );
}
