/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateJobActivitiesRequest = {
  /**
   * UUID of the Job Activity
   */
  uuid: string;
  /**
   * Job Activity fields to update
   */
  jobActivityCreate: components.JobActivityCreate;
};

/** @internal */
export const UpdateJobActivitiesRequest$inboundSchema: z.ZodType<
  UpdateJobActivitiesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  JobActivityCreate: components.JobActivityCreate$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "JobActivityCreate": "jobActivityCreate",
  });
});

/** @internal */
export type UpdateJobActivitiesRequest$Outbound = {
  uuid: string;
  JobActivityCreate: components.JobActivityCreate$Outbound;
};

/** @internal */
export const UpdateJobActivitiesRequest$outboundSchema: z.ZodType<
  UpdateJobActivitiesRequest$Outbound,
  z.ZodTypeDef,
  UpdateJobActivitiesRequest
> = z.object({
  uuid: z.string(),
  jobActivityCreate: components.JobActivityCreate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    jobActivityCreate: "JobActivityCreate",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateJobActivitiesRequest$ {
  /** @deprecated use `UpdateJobActivitiesRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateJobActivitiesRequest$inboundSchema;
  /** @deprecated use `UpdateJobActivitiesRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateJobActivitiesRequest$outboundSchema;
  /** @deprecated use `UpdateJobActivitiesRequest$Outbound` instead. */
  export type Outbound = UpdateJobActivitiesRequest$Outbound;
}

export function updateJobActivitiesRequestToJSON(
  updateJobActivitiesRequest: UpdateJobActivitiesRequest,
): string {
  return JSON.stringify(
    UpdateJobActivitiesRequest$outboundSchema.parse(updateJobActivitiesRequest),
  );
}

export function updateJobActivitiesRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateJobActivitiesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateJobActivitiesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateJobActivitiesRequest' from JSON`,
  );
}
