/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateDocumentTemplatesRequest = {
  /**
   * UUID of the Document Template
   */
  uuid: string;
  /**
   * Document Template fields to update
   */
  documentTemplate: components.DocumentTemplateInput;
};

/** @internal */
export const UpdateDocumentTemplatesRequest$inboundSchema: z.ZodType<
  UpdateDocumentTemplatesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  DocumentTemplate: components.DocumentTemplateInput$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "DocumentTemplate": "documentTemplate",
  });
});

/** @internal */
export type UpdateDocumentTemplatesRequest$Outbound = {
  uuid: string;
  DocumentTemplate: components.DocumentTemplateInput$Outbound;
};

/** @internal */
export const UpdateDocumentTemplatesRequest$outboundSchema: z.ZodType<
  UpdateDocumentTemplatesRequest$Outbound,
  z.ZodTypeDef,
  UpdateDocumentTemplatesRequest
> = z.object({
  uuid: z.string(),
  documentTemplate: components.DocumentTemplateInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    documentTemplate: "DocumentTemplate",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDocumentTemplatesRequest$ {
  /** @deprecated use `UpdateDocumentTemplatesRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateDocumentTemplatesRequest$inboundSchema;
  /** @deprecated use `UpdateDocumentTemplatesRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateDocumentTemplatesRequest$outboundSchema;
  /** @deprecated use `UpdateDocumentTemplatesRequest$Outbound` instead. */
  export type Outbound = UpdateDocumentTemplatesRequest$Outbound;
}

export function updateDocumentTemplatesRequestToJSON(
  updateDocumentTemplatesRequest: UpdateDocumentTemplatesRequest,
): string {
  return JSON.stringify(
    UpdateDocumentTemplatesRequest$outboundSchema.parse(
      updateDocumentTemplatesRequest,
    ),
  );
}

export function updateDocumentTemplatesRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDocumentTemplatesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDocumentTemplatesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDocumentTemplatesRequest' from JSON`,
  );
}
