/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateLocationsRequest = {
  /**
   * UUID of the Location
   */
  uuid: string;
  /**
   * Location fields to update
   */
  locationCreate: components.LocationCreate;
};

/** @internal */
export const UpdateLocationsRequest$inboundSchema: z.ZodType<
  UpdateLocationsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  LocationCreate: components.LocationCreate$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "LocationCreate": "locationCreate",
  });
});
/** @internal */
export type UpdateLocationsRequest$Outbound = {
  uuid: string;
  LocationCreate: components.LocationCreate$Outbound;
};

/** @internal */
export const UpdateLocationsRequest$outboundSchema: z.ZodType<
  UpdateLocationsRequest$Outbound,
  z.ZodTypeDef,
  UpdateLocationsRequest
> = z.object({
  uuid: z.string(),
  locationCreate: components.LocationCreate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    locationCreate: "LocationCreate",
  });
});

export function updateLocationsRequestToJSON(
  updateLocationsRequest: UpdateLocationsRequest,
): string {
  return JSON.stringify(
    UpdateLocationsRequest$outboundSchema.parse(updateLocationsRequest),
  );
}
export function updateLocationsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateLocationsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateLocationsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateLocationsRequest' from JSON`,
  );
}
