/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateMaterialsRequest = {
  /**
   * UUID of the Material
   */
  uuid: string;
  /**
   * Material fields to update
   */
  materialCreate: components.MaterialCreate;
};

/** @internal */
export const UpdateMaterialsRequest$inboundSchema: z.ZodType<
  UpdateMaterialsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  MaterialCreate: components.MaterialCreate$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "MaterialCreate": "materialCreate",
  });
});

/** @internal */
export type UpdateMaterialsRequest$Outbound = {
  uuid: string;
  MaterialCreate: components.MaterialCreate$Outbound;
};

/** @internal */
export const UpdateMaterialsRequest$outboundSchema: z.ZodType<
  UpdateMaterialsRequest$Outbound,
  z.ZodTypeDef,
  UpdateMaterialsRequest
> = z.object({
  uuid: z.string(),
  materialCreate: components.MaterialCreate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    materialCreate: "MaterialCreate",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateMaterialsRequest$ {
  /** @deprecated use `UpdateMaterialsRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateMaterialsRequest$inboundSchema;
  /** @deprecated use `UpdateMaterialsRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateMaterialsRequest$outboundSchema;
  /** @deprecated use `UpdateMaterialsRequest$Outbound` instead. */
  export type Outbound = UpdateMaterialsRequest$Outbound;
}

export function updateMaterialsRequestToJSON(
  updateMaterialsRequest: UpdateMaterialsRequest,
): string {
  return JSON.stringify(
    UpdateMaterialsRequest$outboundSchema.parse(updateMaterialsRequest),
  );
}

export function updateMaterialsRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateMaterialsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateMaterialsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateMaterialsRequest' from JSON`,
  );
}
