/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateCategoriesSecurity = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

export type UpdateCategoriesRequest = {
  /**
   * UUID of the Category
   */
  uuid: string;
  /**
   * Category fields to update
   */
  category: components.CategoryInput;
};

export type UpdateCategoriesResponse = components.Result | components.ErrorT;

/** @internal */
export const UpdateCategoriesSecurity$inboundSchema: z.ZodType<
  UpdateCategoriesSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/** @internal */
export type UpdateCategoriesSecurity$Outbound = {
  apiKey?: string | undefined;
  oauth2?: string | undefined;
};

/** @internal */
export const UpdateCategoriesSecurity$outboundSchema: z.ZodType<
  UpdateCategoriesSecurity$Outbound,
  z.ZodTypeDef,
  UpdateCategoriesSecurity
> = z.object({
  apiKey: z.string().optional(),
  oauth2: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCategoriesSecurity$ {
  /** @deprecated use `UpdateCategoriesSecurity$inboundSchema` instead. */
  export const inboundSchema = UpdateCategoriesSecurity$inboundSchema;
  /** @deprecated use `UpdateCategoriesSecurity$outboundSchema` instead. */
  export const outboundSchema = UpdateCategoriesSecurity$outboundSchema;
  /** @deprecated use `UpdateCategoriesSecurity$Outbound` instead. */
  export type Outbound = UpdateCategoriesSecurity$Outbound;
}

export function updateCategoriesSecurityToJSON(
  updateCategoriesSecurity: UpdateCategoriesSecurity,
): string {
  return JSON.stringify(
    UpdateCategoriesSecurity$outboundSchema.parse(updateCategoriesSecurity),
  );
}

export function updateCategoriesSecurityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCategoriesSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCategoriesSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCategoriesSecurity' from JSON`,
  );
}

/** @internal */
export const UpdateCategoriesRequest$inboundSchema: z.ZodType<
  UpdateCategoriesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string(),
  Category: components.CategoryInput$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Category": "category",
  });
});

/** @internal */
export type UpdateCategoriesRequest$Outbound = {
  uuid: string;
  Category: components.CategoryInput$Outbound;
};

/** @internal */
export const UpdateCategoriesRequest$outboundSchema: z.ZodType<
  UpdateCategoriesRequest$Outbound,
  z.ZodTypeDef,
  UpdateCategoriesRequest
> = z.object({
  uuid: z.string(),
  category: components.CategoryInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    category: "Category",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCategoriesRequest$ {
  /** @deprecated use `UpdateCategoriesRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCategoriesRequest$inboundSchema;
  /** @deprecated use `UpdateCategoriesRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCategoriesRequest$outboundSchema;
  /** @deprecated use `UpdateCategoriesRequest$Outbound` instead. */
  export type Outbound = UpdateCategoriesRequest$Outbound;
}

export function updateCategoriesRequestToJSON(
  updateCategoriesRequest: UpdateCategoriesRequest,
): string {
  return JSON.stringify(
    UpdateCategoriesRequest$outboundSchema.parse(updateCategoriesRequest),
  );
}

export function updateCategoriesRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCategoriesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCategoriesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCategoriesRequest' from JSON`,
  );
}

/** @internal */
export const UpdateCategoriesResponse$inboundSchema: z.ZodType<
  UpdateCategoriesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Result$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type UpdateCategoriesResponse$Outbound =
  | components.Result$Outbound
  | components.ErrorT$Outbound;

/** @internal */
export const UpdateCategoriesResponse$outboundSchema: z.ZodType<
  UpdateCategoriesResponse$Outbound,
  z.ZodTypeDef,
  UpdateCategoriesResponse
> = z.union([
  components.Result$outboundSchema,
  components.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCategoriesResponse$ {
  /** @deprecated use `UpdateCategoriesResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateCategoriesResponse$inboundSchema;
  /** @deprecated use `UpdateCategoriesResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateCategoriesResponse$outboundSchema;
  /** @deprecated use `UpdateCategoriesResponse$Outbound` instead. */
  export type Outbound = UpdateCategoriesResponse$Outbound;
}

export function updateCategoriesResponseToJSON(
  updateCategoriesResponse: UpdateCategoriesResponse,
): string {
  return JSON.stringify(
    UpdateCategoriesResponse$outboundSchema.parse(updateCategoriesResponse),
  );
}

export function updateCategoriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCategoriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCategoriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCategoriesResponse' from JSON`,
  );
}
