/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ArchiveRequest = {
  archived?: boolean | undefined;
  reason?: string | null | undefined;
};

/** @internal */
export const ArchiveRequest$inboundSchema: z.ZodType<
  ArchiveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  archived: z.boolean().default(true),
  reason: z.nullable(z.string()).optional(),
});
/** @internal */
export type ArchiveRequest$Outbound = {
  archived: boolean;
  reason?: string | null | undefined;
};

/** @internal */
export const ArchiveRequest$outboundSchema: z.ZodType<
  ArchiveRequest$Outbound,
  z.ZodTypeDef,
  ArchiveRequest
> = z.object({
  archived: z.boolean().default(true),
  reason: z.nullable(z.string()).optional(),
});

export function archiveRequestToJSON(archiveRequest: ArchiveRequest): string {
  return JSON.stringify(ArchiveRequest$outboundSchema.parse(archiveRequest));
}
export function archiveRequestFromJSON(
  jsonString: string,
): SafeParseResult<ArchiveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArchiveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArchiveRequest' from JSON`,
  );
}
