/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export const AssetTypeActive = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export type AssetTypeActive = ClosedEnum<typeof AssetTypeActive>;

export type AssetType = {
  /**
   * Unique identifier for this record
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.  Valid values are [0,1]
   */
  active?: AssetTypeActive | undefined;
  /**
   * Timestamp at which record was last modified
   */
  editDate?: any | undefined;
  /**
   * The name of the asset type. Used to identify different categories of assets that can be tracked in the system. Examples might include 'Air Conditioner', 'Fire Extinguisher', etc.
   */
  name?: string | undefined;
};

/** @internal */
export const AssetTypeActive$inboundSchema: z.ZodNativeEnum<
  typeof AssetTypeActive
> = z.nativeEnum(AssetTypeActive);
/** @internal */
export const AssetTypeActive$outboundSchema: z.ZodNativeEnum<
  typeof AssetTypeActive
> = AssetTypeActive$inboundSchema;

/** @internal */
export const AssetType$inboundSchema: z.ZodType<
  AssetType,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string().optional(),
  active: AssetTypeActive$inboundSchema.default(1),
  edit_date: z.any().optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "edit_date": "editDate",
  });
});
/** @internal */
export type AssetType$Outbound = {
  uuid?: string | undefined;
  active: number;
  edit_date?: any | undefined;
  name?: string | undefined;
};

/** @internal */
export const AssetType$outboundSchema: z.ZodType<
  AssetType$Outbound,
  z.ZodTypeDef,
  AssetType
> = z.object({
  uuid: z.string().optional(),
  active: AssetTypeActive$outboundSchema.default(1),
  editDate: z.any().optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    editDate: "edit_date",
  });
});

export function assetTypeToJSON(assetType: AssetType): string {
  return JSON.stringify(AssetType$outboundSchema.parse(assetType));
}
export function assetTypeFromJSON(
  jsonString: string,
): SafeParseResult<AssetType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssetType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssetType' from JSON`,
  );
}
