/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export const CompanyContactActive = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export type CompanyContactActive = ClosedEnum<typeof CompanyContactActive>;

/** @internal */
export const CompanyContactActive$inboundSchema: z.ZodNativeEnum<
  typeof CompanyContactActive
> = z.nativeEnum(CompanyContactActive);

/** @internal */
export const CompanyContactActive$outboundSchema: z.ZodNativeEnum<
  typeof CompanyContactActive
> = CompanyContactActive$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompanyContactActive$ {
  /** @deprecated use `CompanyContactActive$inboundSchema` instead. */
  export const inboundSchema = CompanyContactActive$inboundSchema;
  /** @deprecated use `CompanyContactActive$outboundSchema` instead. */
  export const outboundSchema = CompanyContactActive$outboundSchema;
}

export type CompanyContact = {
  /**
   * Unique identifier for this record
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.  Valid values are [0,1]
   */
  active?: CompanyContactActive | undefined;
  /**
   * Timestamp at which record was last modified
   */
  editDate?: any | undefined;
  companyUuid?: string | undefined;
  first?: string | undefined;
  last?: string | undefined;
  phone?: string | undefined;
  mobile?: string | undefined;
  email?: string | undefined;
  type?: string | undefined;
  isPrimaryContact?: string | undefined;
};

export type CompanyContactInput = {
  /**
   * Unique identifier for this record
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.  Valid values are [0,1]
   */
  active?: CompanyContactActive | undefined;
  companyUuid?: string | undefined;
  first?: string | undefined;
  last?: string | undefined;
  phone?: string | undefined;
  mobile?: string | undefined;
  email?: string | undefined;
  type?: string | undefined;
  isPrimaryContact?: string | undefined;
};

/** @internal */
export const CompanyContact$inboundSchema: z.ZodType<
  CompanyContact,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string().optional(),
  active: CompanyContactActive$inboundSchema.default(1),
  edit_date: z.any().optional(),
  company_uuid: z.string().optional(),
  first: z.string().optional(),
  last: z.string().optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  email: z.string().optional(),
  type: z.string().optional(),
  is_primary_contact: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "edit_date": "editDate",
    "company_uuid": "companyUuid",
    "is_primary_contact": "isPrimaryContact",
  });
});

/** @internal */
export type CompanyContact$Outbound = {
  uuid?: string | undefined;
  active: number;
  edit_date?: any | undefined;
  company_uuid?: string | undefined;
  first?: string | undefined;
  last?: string | undefined;
  phone?: string | undefined;
  mobile?: string | undefined;
  email?: string | undefined;
  type?: string | undefined;
  is_primary_contact?: string | undefined;
};

/** @internal */
export const CompanyContact$outboundSchema: z.ZodType<
  CompanyContact$Outbound,
  z.ZodTypeDef,
  CompanyContact
> = z.object({
  uuid: z.string().optional(),
  active: CompanyContactActive$outboundSchema.default(1),
  editDate: z.any().optional(),
  companyUuid: z.string().optional(),
  first: z.string().optional(),
  last: z.string().optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  email: z.string().optional(),
  type: z.string().optional(),
  isPrimaryContact: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    editDate: "edit_date",
    companyUuid: "company_uuid",
    isPrimaryContact: "is_primary_contact",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompanyContact$ {
  /** @deprecated use `CompanyContact$inboundSchema` instead. */
  export const inboundSchema = CompanyContact$inboundSchema;
  /** @deprecated use `CompanyContact$outboundSchema` instead. */
  export const outboundSchema = CompanyContact$outboundSchema;
  /** @deprecated use `CompanyContact$Outbound` instead. */
  export type Outbound = CompanyContact$Outbound;
}

export function companyContactToJSON(companyContact: CompanyContact): string {
  return JSON.stringify(CompanyContact$outboundSchema.parse(companyContact));
}

export function companyContactFromJSON(
  jsonString: string,
): SafeParseResult<CompanyContact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompanyContact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompanyContact' from JSON`,
  );
}

/** @internal */
export const CompanyContactInput$inboundSchema: z.ZodType<
  CompanyContactInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string().optional(),
  active: CompanyContactActive$inboundSchema.default(1),
  company_uuid: z.string().optional(),
  first: z.string().optional(),
  last: z.string().optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  email: z.string().optional(),
  type: z.string().optional(),
  is_primary_contact: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "company_uuid": "companyUuid",
    "is_primary_contact": "isPrimaryContact",
  });
});

/** @internal */
export type CompanyContactInput$Outbound = {
  uuid?: string | undefined;
  active: number;
  company_uuid?: string | undefined;
  first?: string | undefined;
  last?: string | undefined;
  phone?: string | undefined;
  mobile?: string | undefined;
  email?: string | undefined;
  type?: string | undefined;
  is_primary_contact?: string | undefined;
};

/** @internal */
export const CompanyContactInput$outboundSchema: z.ZodType<
  CompanyContactInput$Outbound,
  z.ZodTypeDef,
  CompanyContactInput
> = z.object({
  uuid: z.string().optional(),
  active: CompanyContactActive$outboundSchema.default(1),
  companyUuid: z.string().optional(),
  first: z.string().optional(),
  last: z.string().optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  email: z.string().optional(),
  type: z.string().optional(),
  isPrimaryContact: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyUuid: "company_uuid",
    isPrimaryContact: "is_primary_contact",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompanyContactInput$ {
  /** @deprecated use `CompanyContactInput$inboundSchema` instead. */
  export const inboundSchema = CompanyContactInput$inboundSchema;
  /** @deprecated use `CompanyContactInput$outboundSchema` instead. */
  export const outboundSchema = CompanyContactInput$outboundSchema;
  /** @deprecated use `CompanyContactInput$Outbound` instead. */
  export type Outbound = CompanyContactInput$Outbound;
}

export function companyContactInputToJSON(
  companyContactInput: CompanyContactInput,
): string {
  return JSON.stringify(
    CompanyContactInput$outboundSchema.parse(companyContactInput),
  );
}

export function companyContactInputFromJSON(
  jsonString: string,
): SafeParseResult<CompanyContactInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompanyContactInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompanyContactInput' from JSON`,
  );
}
