/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Record active/deleted flag.
 *
 * @remarks
 *
 * Valid values are [0,1]
 */
export const FormResponseActive = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Record active/deleted flag.
 *
 * @remarks
 *
 * Valid values are [0,1]
 */
export type FormResponseActive = ClosedEnum<typeof FormResponseActive>;

export type FormResponse = {
  /**
   * Record UUID key
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.
   *
   * @remarks
   *
   * Valid values are [0,1]
   */
  active?: FormResponseActive | undefined;
  /**
   * Record last modified timestamp
   */
  editDate?: string | undefined;
  formUuid?: string | undefined;
  staffUuid?: string | undefined;
  regardingObject?: string | undefined;
  regardingObjectUuid?: string | undefined;
  fieldData?: string | undefined;
  timestamp?: string | undefined;
  formByStaffUuid?: string | undefined;
  documentAttachmentUuid?: string | undefined;
  assetUuid?: string | undefined;
};

export type FormResponseInput = {
  /**
   * Record UUID key
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.
   *
   * @remarks
   *
   * Valid values are [0,1]
   */
  active?: FormResponseActive | undefined;
  formUuid?: string | undefined;
  staffUuid?: string | undefined;
  regardingObject?: string | undefined;
  regardingObjectUuid?: string | undefined;
  fieldData?: string | undefined;
  timestamp?: string | undefined;
  formByStaffUuid?: string | undefined;
  documentAttachmentUuid?: string | undefined;
  assetUuid?: string | undefined;
};

/** @internal */
export const FormResponseActive$inboundSchema: z.ZodNativeEnum<
  typeof FormResponseActive
> = z.nativeEnum(FormResponseActive);

/** @internal */
export const FormResponseActive$outboundSchema: z.ZodNativeEnum<
  typeof FormResponseActive
> = FormResponseActive$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FormResponseActive$ {
  /** @deprecated use `FormResponseActive$inboundSchema` instead. */
  export const inboundSchema = FormResponseActive$inboundSchema;
  /** @deprecated use `FormResponseActive$outboundSchema` instead. */
  export const outboundSchema = FormResponseActive$outboundSchema;
}

/** @internal */
export const FormResponse$inboundSchema: z.ZodType<
  FormResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string().optional(),
  active: FormResponseActive$inboundSchema.default(1),
  edit_date: z.string().optional(),
  form_uuid: z.string().optional(),
  staff_uuid: z.string().optional(),
  regarding_object: z.string().optional(),
  regarding_object_uuid: z.string().optional(),
  field_data: z.string().optional(),
  timestamp: z.string().optional(),
  form_by_staff_uuid: z.string().optional(),
  document_attachment_uuid: z.string().optional(),
  asset_uuid: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "edit_date": "editDate",
    "form_uuid": "formUuid",
    "staff_uuid": "staffUuid",
    "regarding_object": "regardingObject",
    "regarding_object_uuid": "regardingObjectUuid",
    "field_data": "fieldData",
    "form_by_staff_uuid": "formByStaffUuid",
    "document_attachment_uuid": "documentAttachmentUuid",
    "asset_uuid": "assetUuid",
  });
});

/** @internal */
export type FormResponse$Outbound = {
  uuid?: string | undefined;
  active: number;
  edit_date?: string | undefined;
  form_uuid?: string | undefined;
  staff_uuid?: string | undefined;
  regarding_object?: string | undefined;
  regarding_object_uuid?: string | undefined;
  field_data?: string | undefined;
  timestamp?: string | undefined;
  form_by_staff_uuid?: string | undefined;
  document_attachment_uuid?: string | undefined;
  asset_uuid?: string | undefined;
};

/** @internal */
export const FormResponse$outboundSchema: z.ZodType<
  FormResponse$Outbound,
  z.ZodTypeDef,
  FormResponse
> = z.object({
  uuid: z.string().optional(),
  active: FormResponseActive$outboundSchema.default(1),
  editDate: z.string().optional(),
  formUuid: z.string().optional(),
  staffUuid: z.string().optional(),
  regardingObject: z.string().optional(),
  regardingObjectUuid: z.string().optional(),
  fieldData: z.string().optional(),
  timestamp: z.string().optional(),
  formByStaffUuid: z.string().optional(),
  documentAttachmentUuid: z.string().optional(),
  assetUuid: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    editDate: "edit_date",
    formUuid: "form_uuid",
    staffUuid: "staff_uuid",
    regardingObject: "regarding_object",
    regardingObjectUuid: "regarding_object_uuid",
    fieldData: "field_data",
    formByStaffUuid: "form_by_staff_uuid",
    documentAttachmentUuid: "document_attachment_uuid",
    assetUuid: "asset_uuid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FormResponse$ {
  /** @deprecated use `FormResponse$inboundSchema` instead. */
  export const inboundSchema = FormResponse$inboundSchema;
  /** @deprecated use `FormResponse$outboundSchema` instead. */
  export const outboundSchema = FormResponse$outboundSchema;
  /** @deprecated use `FormResponse$Outbound` instead. */
  export type Outbound = FormResponse$Outbound;
}

export function formResponseToJSON(formResponse: FormResponse): string {
  return JSON.stringify(FormResponse$outboundSchema.parse(formResponse));
}

export function formResponseFromJSON(
  jsonString: string,
): SafeParseResult<FormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormResponse' from JSON`,
  );
}

/** @internal */
export const FormResponseInput$inboundSchema: z.ZodType<
  FormResponseInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: z.string().optional(),
  active: FormResponseActive$inboundSchema.default(1),
  form_uuid: z.string().optional(),
  staff_uuid: z.string().optional(),
  regarding_object: z.string().optional(),
  regarding_object_uuid: z.string().optional(),
  field_data: z.string().optional(),
  timestamp: z.string().optional(),
  form_by_staff_uuid: z.string().optional(),
  document_attachment_uuid: z.string().optional(),
  asset_uuid: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "form_uuid": "formUuid",
    "staff_uuid": "staffUuid",
    "regarding_object": "regardingObject",
    "regarding_object_uuid": "regardingObjectUuid",
    "field_data": "fieldData",
    "form_by_staff_uuid": "formByStaffUuid",
    "document_attachment_uuid": "documentAttachmentUuid",
    "asset_uuid": "assetUuid",
  });
});

/** @internal */
export type FormResponseInput$Outbound = {
  uuid?: string | undefined;
  active: number;
  form_uuid?: string | undefined;
  staff_uuid?: string | undefined;
  regarding_object?: string | undefined;
  regarding_object_uuid?: string | undefined;
  field_data?: string | undefined;
  timestamp?: string | undefined;
  form_by_staff_uuid?: string | undefined;
  document_attachment_uuid?: string | undefined;
  asset_uuid?: string | undefined;
};

/** @internal */
export const FormResponseInput$outboundSchema: z.ZodType<
  FormResponseInput$Outbound,
  z.ZodTypeDef,
  FormResponseInput
> = z.object({
  uuid: z.string().optional(),
  active: FormResponseActive$outboundSchema.default(1),
  formUuid: z.string().optional(),
  staffUuid: z.string().optional(),
  regardingObject: z.string().optional(),
  regardingObjectUuid: z.string().optional(),
  fieldData: z.string().optional(),
  timestamp: z.string().optional(),
  formByStaffUuid: z.string().optional(),
  documentAttachmentUuid: z.string().optional(),
  assetUuid: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    formUuid: "form_uuid",
    staffUuid: "staff_uuid",
    regardingObject: "regarding_object",
    regardingObjectUuid: "regarding_object_uuid",
    fieldData: "field_data",
    formByStaffUuid: "form_by_staff_uuid",
    documentAttachmentUuid: "document_attachment_uuid",
    assetUuid: "asset_uuid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FormResponseInput$ {
  /** @deprecated use `FormResponseInput$inboundSchema` instead. */
  export const inboundSchema = FormResponseInput$inboundSchema;
  /** @deprecated use `FormResponseInput$outboundSchema` instead. */
  export const outboundSchema = FormResponseInput$outboundSchema;
  /** @deprecated use `FormResponseInput$Outbound` instead. */
  export type Outbound = FormResponseInput$Outbound;
}

export function formResponseInputToJSON(
  formResponseInput: FormResponseInput,
): string {
  return JSON.stringify(
    FormResponseInput$outboundSchema.parse(formResponseInput),
  );
}

export function formResponseInputFromJSON(
  jsonString: string,
): SafeParseResult<FormResponseInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormResponseInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormResponseInput' from JSON`,
  );
}
