/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export const JobPaymentActive = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export type JobPaymentActive = ClosedEnum<typeof JobPaymentActive>;

/**
 * Boolean flag indicating whether this payment represents a deposit against future work (true) rather than a payment for completed work (false). Read-only in the API. (Read only).  Valid values are [0,1]
 */
export const IsDeposit = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Boolean flag indicating whether this payment represents a deposit against future work (true) rather than a payment for completed work (false). Read-only in the API. (Read only).  Valid values are [0,1]
 */
export type IsDeposit = ClosedEnum<typeof IsDeposit>;

export type JobPayment = {
  /**
   * UUID of the job this payment is associated with. Each payment must be linked to a valid job in the system.
   */
  jobUuid?: string | undefined;
  /**
   * UUID of the staff member who recorded or processed this payment. Used for tracking which staff member handled the transaction.
   */
  actionedByUuid?: string | undefined;
  /**
   * The date and time when this payment was recorded or processed. Format is YYYY-MM-DD HH:MM:SS. Used for payment reconciliation and reporting.
   */
  timestamp?: string | undefined;
  /**
   * The payment amount in the account's currency.
   */
  amount?: string | undefined;
  /**
   * The payment method used for this transaction. Examples include 'Cash', 'Credit Card', 'Bank Transfer', 'Stripe', etc.
   */
  method?: string | undefined;
  /**
   * Optional text field for storing additional information about the payment. Can be used to record reference numbers, transaction IDs, or other payment-specific details.
   */
  note?: string | undefined;
  /**
   * UUID linking to a stored attachment related to this payment, such as a receipt image. This is an optional reference to an Attachment record.
   */
  attachmentUuid?: string | undefined;
  /**
   * Unique identifier for this record
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.  Valid values are [0,1]
   */
  active?: JobPaymentActive | undefined;
  /**
   * Timestamp at which record was last modified
   */
  editDate?: any | undefined;
  /**
   * Boolean flag indicating whether this payment represents a deposit against future work (true) rather than a payment for completed work (false). Read-only in the API. (Read only).  Valid values are [0,1]
   */
  isDeposit?: IsDeposit | undefined;
};

/** @internal */
export const JobPaymentActive$inboundSchema: z.ZodNativeEnum<
  typeof JobPaymentActive
> = z.nativeEnum(JobPaymentActive);

/** @internal */
export const JobPaymentActive$outboundSchema: z.ZodNativeEnum<
  typeof JobPaymentActive
> = JobPaymentActive$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace JobPaymentActive$ {
  /** @deprecated use `JobPaymentActive$inboundSchema` instead. */
  export const inboundSchema = JobPaymentActive$inboundSchema;
  /** @deprecated use `JobPaymentActive$outboundSchema` instead. */
  export const outboundSchema = JobPaymentActive$outboundSchema;
}

/** @internal */
export const IsDeposit$inboundSchema: z.ZodNativeEnum<typeof IsDeposit> = z
  .nativeEnum(IsDeposit);

/** @internal */
export const IsDeposit$outboundSchema: z.ZodNativeEnum<typeof IsDeposit> =
  IsDeposit$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IsDeposit$ {
  /** @deprecated use `IsDeposit$inboundSchema` instead. */
  export const inboundSchema = IsDeposit$inboundSchema;
  /** @deprecated use `IsDeposit$outboundSchema` instead. */
  export const outboundSchema = IsDeposit$outboundSchema;
}

/** @internal */
export const JobPayment$inboundSchema: z.ZodType<
  JobPayment,
  z.ZodTypeDef,
  unknown
> = z.object({
  job_uuid: z.string().optional(),
  actioned_by_uuid: z.string().optional(),
  timestamp: z.string().optional(),
  amount: z.string().optional(),
  method: z.string().optional(),
  note: z.string().optional(),
  attachment_uuid: z.string().optional(),
  uuid: z.string().optional(),
  active: JobPaymentActive$inboundSchema.default(1),
  edit_date: z.any().optional(),
  is_deposit: IsDeposit$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "job_uuid": "jobUuid",
    "actioned_by_uuid": "actionedByUuid",
    "attachment_uuid": "attachmentUuid",
    "edit_date": "editDate",
    "is_deposit": "isDeposit",
  });
});

/** @internal */
export type JobPayment$Outbound = {
  job_uuid?: string | undefined;
  actioned_by_uuid?: string | undefined;
  timestamp?: string | undefined;
  amount?: string | undefined;
  method?: string | undefined;
  note?: string | undefined;
  attachment_uuid?: string | undefined;
  uuid?: string | undefined;
  active: number;
  edit_date?: any | undefined;
  is_deposit?: number | undefined;
};

/** @internal */
export const JobPayment$outboundSchema: z.ZodType<
  JobPayment$Outbound,
  z.ZodTypeDef,
  JobPayment
> = z.object({
  jobUuid: z.string().optional(),
  actionedByUuid: z.string().optional(),
  timestamp: z.string().optional(),
  amount: z.string().optional(),
  method: z.string().optional(),
  note: z.string().optional(),
  attachmentUuid: z.string().optional(),
  uuid: z.string().optional(),
  active: JobPaymentActive$outboundSchema.default(1),
  editDate: z.any().optional(),
  isDeposit: IsDeposit$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    jobUuid: "job_uuid",
    actionedByUuid: "actioned_by_uuid",
    attachmentUuid: "attachment_uuid",
    editDate: "edit_date",
    isDeposit: "is_deposit",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace JobPayment$ {
  /** @deprecated use `JobPayment$inboundSchema` instead. */
  export const inboundSchema = JobPayment$inboundSchema;
  /** @deprecated use `JobPayment$outboundSchema` instead. */
  export const outboundSchema = JobPayment$outboundSchema;
  /** @deprecated use `JobPayment$Outbound` instead. */
  export type Outbound = JobPayment$Outbound;
}

export function jobPaymentToJSON(jobPayment: JobPayment): string {
  return JSON.stringify(JobPayment$outboundSchema.parse(jobPayment));
}

export function jobPaymentFromJSON(
  jsonString: string,
): SafeParseResult<JobPayment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JobPayment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JobPayment' from JSON`,
  );
}
