/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export const QueueActive = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export type QueueActive = ClosedEnum<typeof QueueActive>;

/**
 * Determines if jobs in this queue require assignment to staff members. If true, jobs must be explicitly assigned to staff. If false, jobs are visible to all staff..  Valid values are [0,1]
 */
export const QueueRequiresAssignment = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Determines if jobs in this queue require assignment to staff members. If true, jobs must be explicitly assigned to staff. If false, jobs are visible to all staff..  Valid values are [0,1]
 */
export type QueueRequiresAssignment = ClosedEnum<
  typeof QueueRequiresAssignment
>;

export type Queue = {
  /**
   * Unique identifier for this record
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.  Valid values are [0,1]
   */
  active?: QueueActive | undefined;
  /**
   * Timestamp at which record was last modified
   */
  editDate?: any | undefined;
  /**
   * Name of the job queue. Used to identify the queue in the system. Examples include 'Workshop', 'Pending Quotes', etc.
   */
  name?: string | undefined;
  /**
   * Default number of days that jobs should remain in this queue before requiring attention. Common values are 7 days (1 week) or 14 days (2 weeks).
   */
  defaultTimeframe?: number | undefined;
  /**
   * Semicolon-delimited list of staff UUIDs who are subscribed to receive notifications for this queue.
   */
  subscribedStaff?: string | undefined;
  /**
   * Determines if jobs in this queue require assignment to staff members. If true, jobs must be explicitly assigned to staff. If false, jobs are visible to all staff..  Valid values are [0,1]
   */
  requiresAssignment?: QueueRequiresAssignment | undefined;
};

/** @internal */
export const QueueActive$inboundSchema: z.ZodNativeEnum<typeof QueueActive> = z
  .nativeEnum(QueueActive);
/** @internal */
export const QueueActive$outboundSchema: z.ZodNativeEnum<typeof QueueActive> =
  QueueActive$inboundSchema;

/** @internal */
export const QueueRequiresAssignment$inboundSchema: z.ZodNativeEnum<
  typeof QueueRequiresAssignment
> = z.nativeEnum(QueueRequiresAssignment);
/** @internal */
export const QueueRequiresAssignment$outboundSchema: z.ZodNativeEnum<
  typeof QueueRequiresAssignment
> = QueueRequiresAssignment$inboundSchema;

/** @internal */
export const Queue$inboundSchema: z.ZodType<Queue, z.ZodTypeDef, unknown> = z
  .object({
    uuid: z.string().optional(),
    active: QueueActive$inboundSchema.default(1),
    edit_date: z.any().optional(),
    name: z.string().optional(),
    default_timeframe: z.number().int().optional(),
    subscribed_staff: z.string().optional(),
    requires_assignment: QueueRequiresAssignment$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "edit_date": "editDate",
      "default_timeframe": "defaultTimeframe",
      "subscribed_staff": "subscribedStaff",
      "requires_assignment": "requiresAssignment",
    });
  });
/** @internal */
export type Queue$Outbound = {
  uuid?: string | undefined;
  active: number;
  edit_date?: any | undefined;
  name?: string | undefined;
  default_timeframe?: number | undefined;
  subscribed_staff?: string | undefined;
  requires_assignment?: number | undefined;
};

/** @internal */
export const Queue$outboundSchema: z.ZodType<
  Queue$Outbound,
  z.ZodTypeDef,
  Queue
> = z.object({
  uuid: z.string().optional(),
  active: QueueActive$outboundSchema.default(1),
  editDate: z.any().optional(),
  name: z.string().optional(),
  defaultTimeframe: z.number().int().optional(),
  subscribedStaff: z.string().optional(),
  requiresAssignment: QueueRequiresAssignment$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    editDate: "edit_date",
    defaultTimeframe: "default_timeframe",
    subscribedStaff: "subscribed_staff",
    requiresAssignment: "requires_assignment",
  });
});

export function queueToJSON(queue: Queue): string {
  return JSON.stringify(Queue$outboundSchema.parse(queue));
}
export function queueFromJSON(
  jsonString: string,
): SafeParseResult<Queue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Queue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Queue' from JSON`,
  );
}
