/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StaffMessageCreate = {
  /**
   * Unique identifier (UUID) of the staff member who sent this message. Identifies the sender of the communication within the system.
   */
  fromStaffUuid?: string | undefined;
  /**
   * Unique identifier (UUID) of the staff member who received this message. Identifies the intended recipient of the communication.
   */
  toStaffUuid?: string | undefined;
  /**
   * The date and time when the message was sent. Format is YYYY-MM-DD HH:MM:SS. This field is automatically set to the current time when a new message is created.
   */
  sentTimestamp?: string | undefined;
  /**
   * The date and time when the message was delivered to the recipient's device. Format is YYYY-MM-DD HH:MM:SS. This field may be null if delivery confirmation is not available.
   */
  deliveredTimestamp?: string | undefined;
  /**
   * The date and time when the message was read by the recipient. Format is YYYY-MM-DD HH:MM:SS. This field may be null if the message has not been read or if read receipts are not available.
   */
  readTimestamp?: string | undefined;
  /**
   * The text content of the message. Supports Unicode characters for international language support. This field contains the actual message being sent between staff members.
   */
  message?: string | undefined;
  /**
   * Unique identifier (UUID) of the job this message is related to. Optional field that links the message to a specific job for context. This field may be null if the message is not related to a specific job.
   */
  regardingJobUuid?: string | undefined;
  /**
   * Unique identifier for this record
   */
  uuid?: string | undefined;
  attachedJson?: string | undefined;
};

/** @internal */
export const StaffMessageCreate$inboundSchema: z.ZodType<
  StaffMessageCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  from_staff_uuid: z.string().optional(),
  to_staff_uuid: z.string().optional(),
  sent_timestamp: z.string().optional(),
  delivered_timestamp: z.string().optional(),
  read_timestamp: z.string().optional(),
  message: z.string().optional(),
  regarding_job_uuid: z.string().optional(),
  uuid: z.string().optional(),
  attached_json: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "from_staff_uuid": "fromStaffUuid",
    "to_staff_uuid": "toStaffUuid",
    "sent_timestamp": "sentTimestamp",
    "delivered_timestamp": "deliveredTimestamp",
    "read_timestamp": "readTimestamp",
    "regarding_job_uuid": "regardingJobUuid",
    "attached_json": "attachedJson",
  });
});

/** @internal */
export type StaffMessageCreate$Outbound = {
  from_staff_uuid?: string | undefined;
  to_staff_uuid?: string | undefined;
  sent_timestamp?: string | undefined;
  delivered_timestamp?: string | undefined;
  read_timestamp?: string | undefined;
  message?: string | undefined;
  regarding_job_uuid?: string | undefined;
  uuid?: string | undefined;
  attached_json?: string | undefined;
};

/** @internal */
export const StaffMessageCreate$outboundSchema: z.ZodType<
  StaffMessageCreate$Outbound,
  z.ZodTypeDef,
  StaffMessageCreate
> = z.object({
  fromStaffUuid: z.string().optional(),
  toStaffUuid: z.string().optional(),
  sentTimestamp: z.string().optional(),
  deliveredTimestamp: z.string().optional(),
  readTimestamp: z.string().optional(),
  message: z.string().optional(),
  regardingJobUuid: z.string().optional(),
  uuid: z.string().optional(),
  attachedJson: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    fromStaffUuid: "from_staff_uuid",
    toStaffUuid: "to_staff_uuid",
    sentTimestamp: "sent_timestamp",
    deliveredTimestamp: "delivered_timestamp",
    readTimestamp: "read_timestamp",
    regardingJobUuid: "regarding_job_uuid",
    attachedJson: "attached_json",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StaffMessageCreate$ {
  /** @deprecated use `StaffMessageCreate$inboundSchema` instead. */
  export const inboundSchema = StaffMessageCreate$inboundSchema;
  /** @deprecated use `StaffMessageCreate$outboundSchema` instead. */
  export const outboundSchema = StaffMessageCreate$outboundSchema;
  /** @deprecated use `StaffMessageCreate$Outbound` instead. */
  export type Outbound = StaffMessageCreate$Outbound;
}

export function staffMessageCreateToJSON(
  staffMessageCreate: StaffMessageCreate,
): string {
  return JSON.stringify(
    StaffMessageCreate$outboundSchema.parse(staffMessageCreate),
  );
}

export function staffMessageCreateFromJSON(
  jsonString: string,
): SafeParseResult<StaffMessageCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StaffMessageCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StaffMessageCreate' from JSON`,
  );
}
