/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export const VendorActive = {
  Zero: 0,
  One: 1,
} as const;
/**
 * Record active/deleted flag.  Valid values are [0,1]
 */
export type VendorActive = ClosedEnum<typeof VendorActive>;

export type Vendor = {
  /**
   * Company Business Number
   */
  businessNumber?: string | undefined;
  /**
   * Primary email address for the company. Used for system notifications, customer communications, and as the default sender address for emails sent from the system.
   */
  email?: string | undefined;
  /**
   * Accounts/billing email accounts configured for the company.
   */
  emailAccounts?: string | undefined;
  /**
   * The company's billing address where invoices and financial correspondence should be sent.
   */
  billingAddress?: string | undefined;
  /**
   * DEPRECATED
   */
  acceptedPaymentMethods?: any | undefined;
  /**
   * Default geographic region for the company. Affects currency, tax calculations, date formats, and other region-specific behaviors in the system.
   */
  defaultRegion?: string | undefined;
  /**
   * Three-letter ISO currency code (e.g., 'USD', 'AUD', 'EUR') representing the company's primary currency. Used for all financial calculations and displays in the system.
   */
  currency?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business opens on Monday. For example, 480 represents 8:00 AM (8 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  openingTimeMonday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business closes on Monday. For example, 1020 represents 5:00 PM (17 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  closingTimeMonday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business opens on Tuesday. For example, 480 represents 8:00 AM (8 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  openingTimeTuesday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business closes on Tuesday. For example, 1020 represents 5:00 PM (17 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  closingTimeTuesday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business opens on Wednesday. For example, 480 represents 8:00 AM (8 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  openingTimeWednesday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business closes on Wednesday. For example, 1020 represents 5:00 PM (17 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  closingTimeWednesday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business opens on Thursday. For example, 480 represents 8:00 AM (8 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  openingTimeThursday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business closes on Thursday. For example, 1020 represents 5:00 PM (17 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  closingTimeThursday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business opens on Friday. For example, 480 represents 8:00 AM (8 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  openingTimeFriday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business closes on Friday. For example, 1020 represents 5:00 PM (17 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  closingTimeFriday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business opens on Saturday. For example, 480 represents 8:00 AM (8 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  openingTimeSaturday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business closes on Saturday. For example, 1020 represents 5:00 PM (17 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  closingTimeSaturday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business opens on Sunday. For example, 480 represents 8:00 AM (8 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  openingTimeSunday?: string | undefined;
  /**
   * The minute of the day (from midnight) when the business closes on Sunday. For example, 1020 represents 5:00 PM (17 hours × 60 minutes). Used for scheduling and availability calculations.
   */
  closingTimeSunday?: string | undefined;
  /**
   * IANA timezone name (e.g., 'America/New_York', 'Australia/Sydney') for the company's primary location. Used for date/time calculations, scheduling, and display of times across the system.
   */
  timezoneName?: string | undefined;
  /**
   * Text describing the payment terms that appear on invoices. For example, '14 days', 'Net 30', etc. Used to communicate payment expectations to customers on invoices and financial documents.
   */
  invoiceTerms?: string | undefined;
  /**
   * Default status for new jobs created in the system. Valid values are 'Quote' or 'Work Order'. Controls the initial state of newly created jobs.
   */
  jobDefaultStatus?: string | undefined;
  /**
   * Unique identifier for this record
   */
  uuid?: string | undefined;
  /**
   * Record active/deleted flag.  Valid values are [0,1]
   */
  active?: VendorActive | undefined;
  /**
   * Timestamp at which record was last modified
   */
  editDate?: any | undefined;
  /**
   * Company Name
   */
  name: string;
  abnNumber?: string | undefined;
  /**
   * Company Website address
   */
  website?: string | undefined;
};

/** @internal */
export const VendorActive$inboundSchema: z.ZodNativeEnum<typeof VendorActive> =
  z.nativeEnum(VendorActive);
/** @internal */
export const VendorActive$outboundSchema: z.ZodNativeEnum<typeof VendorActive> =
  VendorActive$inboundSchema;

/** @internal */
export const Vendor$inboundSchema: z.ZodType<Vendor, z.ZodTypeDef, unknown> = z
  .object({
    business_number: z.string().optional(),
    email: z.string().optional(),
    email_accounts: z.string().optional(),
    billing_address: z.string().optional(),
    accepted_payment_methods: z.any().optional(),
    default_region: z.string().optional(),
    currency: z.string().optional(),
    opening_time_monday: z.string().optional(),
    closing_time_monday: z.string().optional(),
    opening_time_tuesday: z.string().optional(),
    closing_time_tuesday: z.string().optional(),
    opening_time_wednesday: z.string().optional(),
    closing_time_wednesday: z.string().optional(),
    opening_time_thursday: z.string().optional(),
    closing_time_thursday: z.string().optional(),
    opening_time_friday: z.string().optional(),
    closing_time_friday: z.string().optional(),
    opening_time_saturday: z.string().optional(),
    closing_time_saturday: z.string().optional(),
    opening_time_sunday: z.string().optional(),
    closing_time_sunday: z.string().optional(),
    timezone_name: z.string().optional(),
    invoice_terms: z.string().optional(),
    job_default_status: z.string().optional(),
    uuid: z.string().optional(),
    active: VendorActive$inboundSchema.default(1),
    edit_date: z.any().optional(),
    name: z.string(),
    abn_number: z.string().optional(),
    website: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "business_number": "businessNumber",
      "email_accounts": "emailAccounts",
      "billing_address": "billingAddress",
      "accepted_payment_methods": "acceptedPaymentMethods",
      "default_region": "defaultRegion",
      "opening_time_monday": "openingTimeMonday",
      "closing_time_monday": "closingTimeMonday",
      "opening_time_tuesday": "openingTimeTuesday",
      "closing_time_tuesday": "closingTimeTuesday",
      "opening_time_wednesday": "openingTimeWednesday",
      "closing_time_wednesday": "closingTimeWednesday",
      "opening_time_thursday": "openingTimeThursday",
      "closing_time_thursday": "closingTimeThursday",
      "opening_time_friday": "openingTimeFriday",
      "closing_time_friday": "closingTimeFriday",
      "opening_time_saturday": "openingTimeSaturday",
      "closing_time_saturday": "closingTimeSaturday",
      "opening_time_sunday": "openingTimeSunday",
      "closing_time_sunday": "closingTimeSunday",
      "timezone_name": "timezoneName",
      "invoice_terms": "invoiceTerms",
      "job_default_status": "jobDefaultStatus",
      "edit_date": "editDate",
      "abn_number": "abnNumber",
    });
  });
/** @internal */
export type Vendor$Outbound = {
  business_number?: string | undefined;
  email?: string | undefined;
  email_accounts?: string | undefined;
  billing_address?: string | undefined;
  accepted_payment_methods?: any | undefined;
  default_region?: string | undefined;
  currency?: string | undefined;
  opening_time_monday?: string | undefined;
  closing_time_monday?: string | undefined;
  opening_time_tuesday?: string | undefined;
  closing_time_tuesday?: string | undefined;
  opening_time_wednesday?: string | undefined;
  closing_time_wednesday?: string | undefined;
  opening_time_thursday?: string | undefined;
  closing_time_thursday?: string | undefined;
  opening_time_friday?: string | undefined;
  closing_time_friday?: string | undefined;
  opening_time_saturday?: string | undefined;
  closing_time_saturday?: string | undefined;
  opening_time_sunday?: string | undefined;
  closing_time_sunday?: string | undefined;
  timezone_name?: string | undefined;
  invoice_terms?: string | undefined;
  job_default_status?: string | undefined;
  uuid?: string | undefined;
  active: number;
  edit_date?: any | undefined;
  name: string;
  abn_number?: string | undefined;
  website?: string | undefined;
};

/** @internal */
export const Vendor$outboundSchema: z.ZodType<
  Vendor$Outbound,
  z.ZodTypeDef,
  Vendor
> = z.object({
  businessNumber: z.string().optional(),
  email: z.string().optional(),
  emailAccounts: z.string().optional(),
  billingAddress: z.string().optional(),
  acceptedPaymentMethods: z.any().optional(),
  defaultRegion: z.string().optional(),
  currency: z.string().optional(),
  openingTimeMonday: z.string().optional(),
  closingTimeMonday: z.string().optional(),
  openingTimeTuesday: z.string().optional(),
  closingTimeTuesday: z.string().optional(),
  openingTimeWednesday: z.string().optional(),
  closingTimeWednesday: z.string().optional(),
  openingTimeThursday: z.string().optional(),
  closingTimeThursday: z.string().optional(),
  openingTimeFriday: z.string().optional(),
  closingTimeFriday: z.string().optional(),
  openingTimeSaturday: z.string().optional(),
  closingTimeSaturday: z.string().optional(),
  openingTimeSunday: z.string().optional(),
  closingTimeSunday: z.string().optional(),
  timezoneName: z.string().optional(),
  invoiceTerms: z.string().optional(),
  jobDefaultStatus: z.string().optional(),
  uuid: z.string().optional(),
  active: VendorActive$outboundSchema.default(1),
  editDate: z.any().optional(),
  name: z.string(),
  abnNumber: z.string().optional(),
  website: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    businessNumber: "business_number",
    emailAccounts: "email_accounts",
    billingAddress: "billing_address",
    acceptedPaymentMethods: "accepted_payment_methods",
    defaultRegion: "default_region",
    openingTimeMonday: "opening_time_monday",
    closingTimeMonday: "closing_time_monday",
    openingTimeTuesday: "opening_time_tuesday",
    closingTimeTuesday: "closing_time_tuesday",
    openingTimeWednesday: "opening_time_wednesday",
    closingTimeWednesday: "closing_time_wednesday",
    openingTimeThursday: "opening_time_thursday",
    closingTimeThursday: "closing_time_thursday",
    openingTimeFriday: "opening_time_friday",
    closingTimeFriday: "closing_time_friday",
    openingTimeSaturday: "opening_time_saturday",
    closingTimeSaturday: "closing_time_saturday",
    openingTimeSunday: "opening_time_sunday",
    closingTimeSunday: "closing_time_sunday",
    timezoneName: "timezone_name",
    invoiceTerms: "invoice_terms",
    jobDefaultStatus: "job_default_status",
    editDate: "edit_date",
    abnNumber: "abn_number",
  });
});

export function vendorToJSON(vendor: Vendor): string {
  return JSON.stringify(Vendor$outboundSchema.parse(vendor));
}
export function vendorFromJSON(
  jsonString: string,
): SafeParseResult<Vendor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Vendor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Vendor' from JSON`,
  );
}
